#!/usr/bin/env python3
"""Refuse to lose a hard-won migration rule.

WHY THIS EXISTS
    The migration catalogue is the most valuable thing in this repository: every entry is a bug that
    cost somebody a day, written down so it costs nobody a day again. Its risk is not corruption, it
    is QUIET EROSION -- an entry dropped during a reshuffle, a merge resolved the lazy way, a
    "tidy-up" that removes a section nobody recognised the value of. Nothing complains, and the loss
    surfaces months later as a bug that was already solved once.

    So the census below is the inventory: every entry id plus a hash of its body. A disappearance is
    a hard failure. A change is reported, never blocked -- editing a rule is normal, losing one is not.

USAGE
    python3 tools/check-catalog-fidelity.py --update    # regenerate the census (review the diff!)
    python3 tools/check-catalog-fidelity.py             # verify; non-zero if an entry vanished

EXIT CODES     0 clean    1 an entry disappeared, or the count fell    2 could not run
"""
import argparse, hashlib, pathlib, re, sys

# An entry id is either a lettered section (## V. ... / ### V42c ...) or a numbered pattern
# (NN. **...**) -- the two shapes the catalogue actually uses.
SECTION_RE = re.compile(r'^#{2,4}\s+(?:§\s*)?([A-Z]{1,2}\d*[a-z]?)[.)]\s', re.M)
PATTERN_RE = re.compile(r'^([A-Z]{1,2}\d*)\.\s+\*\*', re.M)


def entries(text):
    """-> {id: body-hash}. Body runs to the next entry, so an edit changes only its own hash."""
    marks = []
    for rx in (SECTION_RE, PATTERN_RE):
        for m in rx.finditer(text):
            marks.append((m.start(), m.group(1)))
    marks.sort()
    out = {}
    for i, (pos, ident) in enumerate(marks):
        end = marks[i + 1][0] if i + 1 < len(marks) else len(text)
        body = re.sub(r'\s+', ' ', text[pos:end]).strip()
        out[ident] = hashlib.sha1(body.encode()).hexdigest()[:16]
    return out


def collect(root, globs):
    found = {}
    for g in globs:
        for f in sorted(root.glob(g)):
            if f.is_file():
                for ident, h in entries(f.read_text(errors="replace")).items():
                    found[f"{f.relative_to(root)}::{ident}"] = h
    return found


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root", default=".")
    ap.add_argument("--census", default="docs/catalog-census.tsv")
    ap.add_argument("--globs", nargs="*",
                    default=["CATALOG.md", "docs/catalog/*.md", ".claude/skills/*/references/*.md"])
    ap.add_argument("--update", action="store_true")
    a = ap.parse_args()

    root = pathlib.Path(a.root).resolve()
    census = root / a.census
    found = collect(root, a.globs)

    if not found and not census.exists():
        # Chunk 1 state: the gate exists before the catalogue does. Say so out loud -- a check that
        # silently found nothing to do is indistinguishable from one that passed on real content.
        print("check-catalog-fidelity: no catalogue files yet and no census — NOTHING CHECKED.")
        print("                        This is expected only before the catalogue lands.")
        return 0

    if a.update:
        census.parent.mkdir(parents=True, exist_ok=True)
        census.write_text("# entry\tbody-sha1  (generated by tools/check-catalog-fidelity.py --update)\n"
                          + "".join(f"{k}\t{v}\n" for k, v in sorted(found.items())))
        print(f"check-catalog-fidelity: wrote {len(found)} entries -> {census.relative_to(root)}")
        print("                        REVIEW THE DIFF: a removal here is a rule being deleted.")
        return 0

    if not census.exists():
        print(f"check-catalog-fidelity: FAIL — {a.census} is missing but {len(found)} entries exist.",
              file=sys.stderr)
        print("                        Run --update and commit it.", file=sys.stderr)
        return 2

    prev = {}
    for line in census.read_text().splitlines():
        if line.startswith("#") or "\t" not in line:
            continue
        k, v = line.split("\t", 1)
        prev[k] = v.strip()

    gone = sorted(set(prev) - set(found))
    changed = sorted(k for k in set(prev) & set(found) if prev[k] != found[k])
    added = sorted(set(found) - set(prev))

    print(f"check-catalog-fidelity: {len(found)} entries now, {len(prev)} in the census")
    for k in added:
        print(f"  + new     {k}")
    for k in changed:
        print(f"  ~ changed {k}   (edits are fine; this is here so the diff is visible)")

    if gone:
        print(f"\ncheck-catalog-fidelity: FAIL — {len(gone)} entr{'y' if len(gone)==1 else 'ies'} DISAPPEARED:",
              file=sys.stderr)
        for k in gone:
            print(f"  - {k}", file=sys.stderr)
        print("\n  Each of these is a rule somebody paid for. If a removal is genuinely intended,",
              file=sys.stderr)
        print("  rerun with --update and say why in the commit message.", file=sys.stderr)
        return 1

    if len(found) < len(prev):
        print(f"\ncheck-catalog-fidelity: FAIL — entry count fell {len(prev)} -> {len(found)}.",
              file=sys.stderr)
        return 1

    print("check-catalog-fidelity: PASS — nothing lost.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
