#!/usr/bin/env python3
"""Server reload listeners and weighted-random picks, 1.21.1 -> 26.2, keeping every body as written.

    python3 tools/convert-reload-weighted.py --src src/main/java --modid mymod [--package my.mod.compat] [--dry-run]
    python3 tools/convert-reload-weighted.py --self-check

Three changes, each read off the 26.2 jar (CATALOG §V36):

  NAMED LISTENERS.  AddServerReloadListenersEvent.addListener takes (Identifier, PreparableReloadListener): listeners
  are a dependency graph in 26.x and each must be addressable.  Inside a method whose parameter is that event (or the
  1.21.1 AddReloadListenerEvent), `e.addListener(X)` becomes
      e.addListener(Identifier.fromNamespaceAndPath("<modid>", "<name>"), X)
  where <name> is X's own name in snake case (SUMMON_CONFIGS -> summon_configs, new GearConfigReloadListener() ->
  gear_config_reload_listener).  Names are unique across the tree (a clash gets _2, _3).

  JSON LISTENERS.  SimpleJsonResourceReloadListener became generic and codec-driven:
      super(Gson, String dir)  ->  super(ExtraCodecs.JSON, FileToIdConverter.json(dir))
      extends SimpleJsonResourceReloadListener  ->  extends SimpleJsonResourceReloadListener<JsonElement>
  ExtraCodecs.JSON asks for the RAW map, so apply(Map<Identifier, JsonElement>, ...) receives exactly what 1.21.1
  handed it and every body that parses defensively keeps doing so (§V36: a codec-typed listener would take that
  decision away).  The Gson argument is dropped; a Gson expression that is not a plain name or `new Gson()` is NOTED.

  WEIGHTS.  26.2 removed Weight and WeightedEntry (a weight is an int; Weighted<T> is a record) and every
  WeightedRandom method takes a ToIntFunction.  Weight and WeightedEntry are generated into <package> with their
  1.21.1 contract (Weight.of / asInt / CODEC, WeightedEntry.getWeight / wrap / Wrapper), the imports are repointed,
  and the WeightedRandom calls gain `e -> e.getWeight().asInt()` -- so a class that `implements WeightedEntry`
  stays exactly as written.  WeightedRandomList / SimpleWeightedRandomList (26.2: WeightedList, a different API)
  are REFUSED and named.

Writes <package>.Weight and <package>.WeightedEntry (default <the @Mod class's package>.compat) only when a weight
was converted.  Idempotent.  Standard library only.
"""
import argparse, pathlib, re, sys, tempfile

GEN_TAG = "Generated by tools/convert-reload-weighted.py"
EVENTS = r"(?:AddServerReloadListenersEvent|AddReloadListenerEvent)"
EVENT_PARAM = re.compile(r"\(\s*(?:final\s+)?(?:[\w.]+\.)?" + EVENTS + r"\s+(\w+)\s*\)\s*(?:throws[^{]*)?\{")
SJRRL_EXT = re.compile(r"\bextends\s+(?:net\.minecraft\.server\.packs\.resources\.)?SimpleJsonResourceReloadListener\b(?!\s*<)")
WEIGHTED_RANDOM = re.compile(r"\bWeightedRandom\s*\.\s*(getRandomItem|getTotalWeight|getWeightedItem)\s*\(")
WEIGHT_IMPORT = re.compile(r"^import\s+net\.minecraft\.util\.random\.(Weight|WeightedEntry)\s*;", re.M)
WEIGHT_FQ = re.compile(r"\bnet\.minecraft\.util\.random\.(Weight|WeightedEntry)\b(?!\w)")
LIST_TYPES = re.compile(r"\b(?:Simple)?WeightedRandomList\b")
# arity of each 1.21.1 WeightedRandom method (the 26.2 one takes one more argument, the ToIntFunction)
OLD_ARITY = {"getRandomItem": (2, 3), "getTotalWeight": (1,), "getWeightedItem": (2,)}
WEIGHER = "e -> e.getWeight().asInt()"

WEIGHT = """package {pkg};

import com.mojang.serialization.Codec;
import net.minecraft.util.ExtraCodecs;

/** {tag}: 26.2 removed net.minecraft.util.random.Weight (a weight is a plain int now); its 1.21.1 contract. */
public final class Weight {{
    public static final Codec<Weight> CODEC = ExtraCodecs.NON_NEGATIVE_INT.xmap(Weight::of, Weight::asInt);
    private static final Weight ONE = new Weight(1);
    private final int value;

    private Weight(int value) {{
        this.value = value;
    }}

    public static Weight of(int value) {{
        if (value == 1) {{
            return ONE;
        }}
        if (value < 0) {{
            throw new IllegalArgumentException("Weight should be >= 0");
        }}
        return new Weight(value);
    }}

    public int asInt() {{
        return this.value;
    }}

    @Override
    public String toString() {{
        return Integer.toString(this.value);
    }}

    @Override
    public boolean equals(Object o) {{
        return this == o || o instanceof Weight w && w.value == this.value;
    }}

    @Override
    public int hashCode() {{
        return Integer.hashCode(this.value);
    }}
}}
"""

ENTRY = """package {pkg};

/** {tag}: 26.2 removed net.minecraft.util.random.WeightedEntry; its 1.21.1 contract, unchanged. */
public interface WeightedEntry {{
    Weight getWeight();

    static <T> Wrapper<T> wrap(T data, int weight) {{
        return new Wrapper<>(data, Weight.of(weight));
    }}

    record Wrapper<T>(T data, Weight weight) implements WeightedEntry {{
        @Override
        public Weight getWeight() {{
            return this.weight;
        }}
    }}

    class IntrusiveEntry implements WeightedEntry {{
        private final Weight weight;

        public IntrusiveEntry(int weight) {{
            this.weight = Weight.of(weight);
        }}

        public IntrusiveEntry(Weight weight) {{
            this.weight = weight;
        }}

        @Override
        public Weight getWeight() {{
            return this.weight;
        }}
    }}
}}
"""


def mod_package(src):
    for f in sorted(src.rglob("*.java")):
        t = f.read_text(encoding="utf-8", errors="replace")
        if re.search(r"^\s*@Mod\s*\(", t, re.M):
            m = re.search(r"^package\s+([\w.]+)\s*;", t, re.M)
            if m:
                return m.group(1)
    return None


def skip_literal(text, i):
    """i at a quote, // or /*: -> the index just past it (string/char literals and comments are skipped whole)."""
    c = text[i]
    if c in "\"'":
        j = i + 1
        while j < len(text) and text[j] != c:
            j += 2 if text[j] == "\\" else 1
        return j + 1
    if text.startswith("//", i):
        j = text.find("\n", i)
        return len(text) if j < 0 else j
    j = text.find("*/", i + 2)
    return len(text) if j < 0 else j + 2


def match_close(text, i, open_c, close_c):
    """i at open_c: -> the index of its matching close_c, or None."""
    depth = 0
    while i < len(text):
        c = text[i]
        if c in "\"'" or text.startswith("//", i) or text.startswith("/*", i):
            i = skip_literal(text, i)
            continue
        if c == open_c:
            depth += 1
        elif c == close_c:
            depth -= 1
            if depth == 0:
                return i
        i += 1
    return None


def split_args(s):
    out, depth, cur, i = [], 0, "", 0
    while i < len(s):
        c = s[i]
        if c in "\"'":
            j = skip_literal(s, i)
            cur += s[i:j]
            i = j
            continue
        if c in "([{<":
            depth += 1
        elif c in ")]}>":
            depth -= 1
        if c == "," and depth == 0:
            out.append(cur)
            cur = ""
        else:
            cur += c
        i += 1
    if cur.strip() or out:
        out.append(cur)
    return out


def snake(name):
    name = re.sub(r"(?<=[a-z0-9])(?=[A-Z])", "_", name)
    return re.sub(r"[^a-z0-9_]+", "_", name.lower()).strip("_") or "listener"


def listener_name(expr):
    e = expr.strip()
    m = re.match(r"new\s+([\w.]+)\s*(?:<[^>]*>)?\s*\(", e)
    if m:
        return snake(m.group(1).split(".")[-1])
    m = re.fullmatch(r"(?:this\.)?([\w.]+?)(?:\.get\(\))?", e)
    if m:
        return snake(m.group(1).split(".")[-1])
    return "listener"


def add_import(text, fq):
    simple = fq.rsplit(".", 1)[1]
    if re.search(r"^import\s+" + re.escape(fq) + r"\s*;", text, re.M):
        return text
    if re.search(r"^import\s+[\w.]+\." + simple + r"\s*;", text, re.M):
        return text  # another class of that name is imported; the caller writes the name fully qualified
    m = list(re.finditer(r"^import\s[^\n]*;\s*$", text, re.M))
    if m:
        at = m[-1].end()
        return text[:at] + f"\nimport {fq};" + text[at:]
    m = re.search(r"^package\s[^\n]*;\s*$", text, re.M)
    at = m.end() if m else 0
    return text[:at] + f"\n\nimport {fq};" + text[at:]


def convert_listeners(text, modid, used, notes):
    n, out, pos = 0, [], 0
    for m in EVENT_PARAM.finditer(text):
        if m.start() < pos:
            continue
        var, open_b = m.group(1), m.end() - 1
        close_b = match_close(text, open_b, "{", "}")
        if close_b is None:
            continue
        body = text[open_b:close_b]
        new_body, i = "", 0
        call = re.compile(r"\b" + re.escape(var) + r"\s*\.\s*addListener\s*\(")
        for c in call.finditer(body):
            p_open = c.end() - 1
            p_close = match_close(body, p_open, "(", ")")
            if p_close is None:
                continue
            args = split_args(body[p_open + 1:p_close])
            if len(args) != 1:
                continue  # already named, or a shape this does not know
            base = listener_name(args[0])
            name, k = base, 2
            while name in used:
                name, k = f"{base}_{k}", k + 1
            used.add(name)
            new_body += body[i:p_open + 1] + f'Identifier.fromNamespaceAndPath("{modid}", "{name}"), ' + args[0].strip()
            i = p_close
            n += 1
        new_body += body[i:]
        out.append(text[pos:open_b] + new_body)
        pos = close_b
    out.append(text[pos:])
    text = "".join(out)
    if n:
        text = add_import(text, "net.minecraft.resources.Identifier")
    return text, n


def convert_json_listener(text, notes):
    if not SJRRL_EXT.search(text):
        return text, 0
    text = SJRRL_EXT.sub("extends SimpleJsonResourceReloadListener<JsonElement>", text)
    n = 1
    for m in reversed(list(re.finditer(r"\bsuper\s*\(", text))):
        p_close = match_close(text, m.end() - 1, "(", ")")
        if p_close is None:
            continue
        args = split_args(text[m.end():p_close])
        if len(args) != 2:
            continue
        gson, folder = args[0].strip(), args[1].strip()
        if not re.fullmatch(r"(?:this\.)?\w+|new\s+(?:com\.google\.gson\.)?Gson\s*\(\s*\)", gson):
            notes.append(f"the Gson argument `{gson}` is dropped (26.2 parses with ExtraCodecs.JSON): check it had no side effect")
        text = text[:m.start()] + f"super(ExtraCodecs.JSON, FileToIdConverter.json({folder}))" + text[p_close + 1:]
    for fq in ("com.google.gson.JsonElement", "net.minecraft.util.ExtraCodecs", "net.minecraft.resources.FileToIdConverter"):
        text = add_import(text, fq)
    return text, n


def convert_weights(text, pkg):
    n = 0
    for m in reversed(list(WEIGHTED_RANDOM.finditer(text))):
        p_open = m.end() - 1
        p_close = match_close(text, p_open, "(", ")")
        if p_close is None:
            continue
        args = split_args(text[p_open + 1:p_close])
        if len(args) not in OLD_ARITY[m.group(1)] or re.search(r"->|::", args[-1]):
            continue  # already given its ToIntFunction (26.2 shape), or not a 1.21.1 call
        text = text[:p_close] + ", " + WEIGHER + text[p_close:]
        n += 1
    imports = len(WEIGHT_IMPORT.findall(text))
    text = WEIGHT_IMPORT.sub(lambda m: f"import {pkg}.{m.group(1)};", text)
    text, fq = WEIGHT_FQ.subn(lambda m: f"{pkg}.{m.group(1)}", text)
    return text, n, imports + fq


def convert(src, modid, pkg=None, dry=False):
    src = pathlib.Path(src)
    files = sorted(src.rglob("*.java"))
    pkg = pkg or ((mod_package(src) or "") + ".compat").lstrip(".")
    used, changed, counts, notes, refused, weights_used = set(), [], {"listeners": 0, "json": 0, "weighted": 0}, [], [], False
    for f in files:
        t = f.read_text(encoding="utf-8", errors="replace")
        if GEN_TAG in t:
            used.update(re.findall(r'fromNamespaceAndPath\("[^"]*",\s*"([^"]+)"\)', t))
            continue
        used.update(re.findall(r'addListener\(\s*Identifier\.fromNamespaceAndPath\("[^"]*",\s*"([^"]+)"\)', t))
    for f in files:
        t0 = t = f.read_text(encoding="utf-8", errors="replace")
        if GEN_TAG in t:
            continue
        rel = f.relative_to(src)
        fnotes = []
        t, a = convert_listeners(t, modid, used, fnotes)
        t, b = convert_json_listener(t, fnotes)
        t, c, imp = convert_weights(t, pkg)
        if c or imp:
            weights_used = True
        if LIST_TYPES.search(t):
            refused.append(f"{rel}: WeightedRandomList/SimpleWeightedRandomList (26.2: WeightedList, a different API)")
        counts["listeners"] += a
        counts["json"] += b
        counts["weighted"] += c + imp
        notes += [f"{rel}: {x}" for x in fnotes]
        if t != t0:
            changed.append(rel)
            if not dry:
                f.write_text(t, encoding="utf-8")
    if weights_used and pkg and not dry:
        out = src / pkg.replace(".", "/")
        out.mkdir(parents=True, exist_ok=True)
        for name, tmpl in (("Weight", WEIGHT), ("WeightedEntry", ENTRY)):
            (out / f"{name}.java").write_text(tmpl.format(pkg=pkg, tag=GEN_TAG), encoding="utf-8")
    print(f"convert-reload-weighted: {len(changed)} file(s) changed; {counts['listeners']} listener(s) named, "
          f"{counts['json']} JSON listener(s), {counts['weighted']} weight site(s)"
          + (f"; {pkg}.Weight/WeightedEntry" if weights_used else ""))
    for x in notes:
        print(f"  NOTE {x}")
    for x in refused:
        print(f"  REFUSED {x}")
    return changed


SAMPLE = {
    "a/Mod.java": """package a;
@Mod("x")
public class Mod {}
""",
    "a/Reg.java": """package a;
import net.neoforged.neoforge.event.AddServerReloadListenersEvent;
public class Reg {
    public static final Object CONFIGS = null;
    public static void on(AddServerReloadListenersEvent event) {
        event.addListener(CONFIGS);
        event.addListener(new GearConfigReloadListener());
        other.addListener(CONFIGS);
    }
    public static void again(final AddServerReloadListenersEvent e) {
        e.addListener(Holder.CONFIGS);
    }
}
""",
    "a/Data.java": """package a;
import com.google.gson.Gson;
import net.minecraft.server.packs.resources.SimpleJsonResourceReloadListener;
public class Data<T> extends SimpleJsonResourceReloadListener {
    public Data(String folder, Gson gson) {
        super(gson, folder);
    }
}
""",
    "a/Elite.java": """package a;
import net.minecraft.util.random.Weight;
import net.minecraft.util.random.WeightedEntry;
import net.minecraft.util.random.WeightedRandom;
public class Elite implements WeightedEntry {
    public Weight getWeight() { return Weight.of(2); }
    static Object pick(java.util.List<Elite> l, Object r) { return WeightedRandom.getRandomItem(r, l).orElse(null); }
    static int total(java.util.List<Elite> l) { return WeightedRandom.getTotalWeight(l); }
}
""",
}


def self_check():
    ok = True
    with tempfile.TemporaryDirectory() as d:
        src = pathlib.Path(d)
        for rel, body in SAMPLE.items():
            (src / rel).parent.mkdir(parents=True, exist_ok=True)
            (src / rel).write_text(body, encoding="utf-8")
        convert(src, "x")
        reg = (src / "a/Reg.java").read_text(encoding="utf-8")
        ok &= 'event.addListener(Identifier.fromNamespaceAndPath("x", "configs"), CONFIGS);' in reg
        ok &= 'event.addListener(Identifier.fromNamespaceAndPath("x", "gear_config_reload_listener"), new GearConfigReloadListener());' in reg
        ok &= "other.addListener(CONFIGS);" in reg          # not the event: untouched
        ok &= 'fromNamespaceAndPath("x", "configs_2"), Holder.CONFIGS' in reg   # unique across the tree
        ok &= "import net.minecraft.resources.Identifier;" in reg
        data = (src / "a/Data.java").read_text(encoding="utf-8")
        ok &= "extends SimpleJsonResourceReloadListener<JsonElement>" in data
        ok &= "super(ExtraCodecs.JSON, FileToIdConverter.json(folder));" in data
        el = (src / "a/Elite.java").read_text(encoding="utf-8")
        ok &= "import a.compat.Weight;" in el and "import a.compat.WeightedEntry;" in el
        ok &= "getRandomItem(r, l, e -> e.getWeight().asInt())" in el and "getTotalWeight(l, e -> e.getWeight().asInt())" in el
        ok &= (src / "a/compat/Weight.java").exists() and (src / "a/compat/WeightedEntry.java").exists()
        snap = {p: p.read_text(encoding="utf-8") for p in src.rglob("*.java")}
        convert(src, "x")
        ok &= snap == {p: p.read_text(encoding="utf-8") for p in src.rglob("*.java")}     # idempotent
    print("self-check:", "OK" if ok else "FAILED")
    return 0 if ok else 1


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--src")
    ap.add_argument("--modid")
    ap.add_argument("--package", help="where Weight/WeightedEntry go (default: <the @Mod class's package>.compat)")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--self-check", action="store_true")
    a = ap.parse_args()
    if a.self_check:
        return self_check()
    if not (a.src and a.modid):
        ap.error("--src and --modid are required")
    convert(a.src, a.modid, a.package, a.dry_run)
    return 0


if __name__ == "__main__":
    sys.exit(main())
