#!/usr/bin/env python3
"""Move 1.21.1 SavedData (Factory + a name string, save(CompoundTag, Provider)) to 26.2 (SavedDataType + a Codec),
keeping every hand-written load and save body byte-identical.

    python3 tools/convert-saved-data.py --src src/main/java --modid <modid> [--package my.mod.compat] [--dry-run]
    python3 tools/convert-saved-data.py --self-check

26.2 stripped SavedData down to its dirty flag (no save method at all), removed SavedData.Factory and
DimensionDataStorage, and keys a store by a SavedDataType(Identifier, constructor, Codec) instead of a name string
(CATALOG §V29). A 1.21.1 store's load and save are usually written to be FORGIVING (a default per key, skip a bad
record), and a generated field-by-field codec would fail the whole decode on one bad entry. So nothing is rewritten
into a codec: the generated <package>.SavedDataCompat bridges the old shape onto CompoundTag.CODEC and the store's own
load/save keep doing the work, so the saved content is unchanged.

  class X extends SavedData                         ->  class X extends <pkg>.SavedDataCompat.Base
                                                        (Base re-declares save(CompoundTag, Provider), so every
                                                        @Override stays valid and the body is untouched)
  SavedData.Factory / import ...SavedData.Factory   ->  <pkg>.SavedDataCompat.Factory   (same record shape: a
                                                        Supplier, a (CompoundTag, Provider) loader, a DataFixTypes)
  <storage>.computeIfAbsent(factory, name)          ->  <storage>.computeIfAbsent(<pkg>.SavedDataCompat.type(factory, name))
  <storage>.get(factory, name)                      ->  <storage>.get(<pkg>.SavedDataCompat.type(factory, name))
  DimensionDataStorage                              ->  net.minecraft.world.level.storage.SavedDataStorage

where <storage> is a getDataStorage() call or a variable declared DimensionDataStorage (a Map.computeIfAbsent is
never touched).

THE PROVIDER.  NeoForge 26.2 hands a SavedDataType's factories the ServerLevel (patched SavedDataType.Factory), so
the bridge gives load AND save that level's registryAccess(), as 1.21.1 did. (null when the storage has no level.)

THE FILE MOVES, and the bridge carries the old one across.  26.2 saves a store at data/<namespace>/<name>.dat where
1.21.1 wrote data/<name>.dat, so a 1.21.1 world's data would silently reset. When no 26.2 file exists yet, the
bridge reads the 1.21.1 file from the same dimension's data folder, loads it with the store's own load, marks it
dirty (so it is written at the new path) and logs one line. The old file is left in place.

REFUSED and named (left untouched): storage.set(name, data) (26.2's set needs the store's type; route it through
computeIfAbsent), a computeIfAbsent/get on storage that is not (factory, name), and a SavedData subclass with no
save(CompoundTag, Provider) (Base makes that a compile error, which is the honest signal).

Writes <package>.SavedDataCompat (default <the @Mod class's package>.compat) when anything changed.  Idempotent.
Standard library only.
"""
import argparse, pathlib, re, sys, tempfile

GEN_TAG = "Generated by tools/convert-saved-data.py"
SD_FQN = "net.minecraft.world.level.saveddata.SavedData"
DDS_FQN = "net.minecraft.world.level.storage.DimensionDataStorage"
SDS_FQN = "net.minecraft.world.level.storage.SavedDataStorage"

COMPAT = """package {pkg};

import com.mojang.logging.LogUtils;
import com.mojang.serialization.Codec;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Locale;
import java.util.function.BiFunction;
import java.util.function.Supplier;
import net.minecraft.SharedConstants;
import net.minecraft.core.HolderLookup;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.resources.Identifier;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.util.datafix.DataFixTypes;
import net.minecraft.world.level.dimension.DimensionType;
import net.minecraft.world.level.saveddata.SavedData;
import net.minecraft.world.level.saveddata.SavedDataType;
import net.minecraft.world.level.storage.LevelResource;
import org.slf4j.Logger;

/**
 * {tag}. The 1.21.1 SavedData shape (Factory + name, save(CompoundTag, Provider)) on 26.2's
 * SavedDataType. The store's own load and save do the work over CompoundTag.CODEC, so the saved content is what
 * 1.21.1 wrote. 26.2 keeps the file at data/{modid}/&lt;name&gt;.dat; a 1.21.1 file at data/&lt;name&gt;.dat is read
 * once when no 26.2 file exists yet (CATALOG V29).
 */
public final class SavedDataCompat {{
    private static final Logger LOGGER = LogUtils.getLogger();
    private static final String NAMESPACE = "{modid}";

    private SavedDataCompat() {{
    }}

    /** 1.21.1's SavedData: 26.2 dropped save(), so it is declared here for the store to keep overriding. */
    public abstract static class Base extends SavedData {{
        public abstract CompoundTag save(CompoundTag tag, HolderLookup.Provider registries);
    }}

    /** 1.21.1's SavedData.Factory. */
    public record Factory<T extends Base>(Supplier<T> constructor, BiFunction<CompoundTag, HolderLookup.Provider, T> deserializer,
                                          DataFixTypes type) {{
        public Factory(Supplier<T> constructor, BiFunction<CompoundTag, HolderLookup.Provider, T> deserializer) {{
            this(constructor, deserializer, null);
        }}
    }}

    public static <T extends Base> SavedDataType<T> type(Factory<T> factory, String name) {{
        int colon = name.indexOf(':');
        Identifier id = colon < 0 ? Identifier.fromNamespaceAndPath(NAMESPACE, path(name))
                                  : Identifier.fromNamespaceAndPath(name.substring(0, colon), path(name.substring(colon + 1)));
        return new SavedDataType<>(id, level -> create(factory, name, level), level -> codec(factory, level), factory.type());
    }}

    private static String path(String s) {{
        return s.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9/._-]", "_");
    }}

    private static HolderLookup.Provider registries(ServerLevel level) {{
        return level == null ? null : level.registryAccess();
    }}

    private static <T extends Base> Codec<T> codec(Factory<T> factory, ServerLevel level) {{
        return CompoundTag.CODEC.xmap(tag -> factory.deserializer().apply(tag, registries(level)),
                                      data -> data.save(new CompoundTag(), registries(level)));
    }}

    /** A fresh store, or the one a 1.21.1 world saved at data/&lt;name&gt;.dat in this dimension. */
    private static <T extends Base> T create(Factory<T> factory, String name, ServerLevel level) {{
        if (level != null) {{
            Path legacy = DimensionType.getStorageFolder(level.dimension(), level.getServer().getWorldPath(LevelResource.ROOT))
                .resolve("data").resolve(name + ".dat");
            if (Files.isRegularFile(legacy)) {{
                try {{
                    CompoundTag root = level.getDataStorage().readTagFromDisk(legacy, null,
                        SharedConstants.getCurrentVersion().dataVersion().version());
                    T data = factory.deserializer().apply(root.getCompoundOrEmpty("data"), registries(level));
                    data.setDirty();
                    LOGGER.info("Read 1.21.1 saved data {{}} for {{}}; it is saved under data/{{}}/ from now on", legacy, name, NAMESPACE);
                    return data;
                }} catch (IOException | RuntimeException e) {{
                    LOGGER.error("Could not read 1.21.1 saved data {{}}; starting it empty", legacy, e);
                }}
            }}
        }}
        return factory.constructor().get();
    }}
}}
"""


def mod_package(src):
    for f in sorted(src.rglob("*.java")):
        t = f.read_text(encoding="utf-8", errors="replace")
        if re.search(r"^\s*@(?:net\.neoforged\.fml\.common\.)?Mod\s*\(", t, re.M):
            m = re.search(r"^package\s+([\w.]+)\s*;", t, re.M)
            if m:
                return m.group(1)
    return None


def skip_literal(text, i):
    c = text[i]
    if c in "\"'":
        j = i + 1
        while j < len(text) and text[j] != c:
            j += 2 if text[j] == "\\" else 1
        return j + 1
    if text.startswith("//", i):
        j = text.find("\n", i)
        return len(text) if j < 0 else j
    j = text.find("*/", i + 2)
    return len(text) if j < 0 else j + 2


def match_close(text, i):
    """i at '(': -> the index of its matching ')', or None."""
    depth = 0
    while i < len(text):
        c = text[i]
        if c in "\"'" or text.startswith("//", i) or text.startswith("/*", i):
            i = skip_literal(text, i)
            continue
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
            if depth == 0:
                return i
        i += 1
    return None


def split_args(s):
    out, depth, cur, i = [], 0, "", 0
    while i < len(s):
        c = s[i]
        if c in "\"'":
            j = skip_literal(s, i)
            cur += s[i:j]
            i = j
            continue
        if c == "-" and s.startswith("->", i):      # a lambda arrow is not a closing generic bracket
            cur += "->"
            i += 2
            continue
        if c in "([{<":
            depth += 1
        elif c in ")]}>":
            depth -= 1
        if c == "," and depth == 0:
            out.append(cur)
            cur = ""
        else:
            cur += c
        i += 1
    if cur.strip() or out:
        out.append(cur)
    return out


def line_of(text, i):
    return text.count("\n", 0, i) + 1


def code_mask(text):
    """-> a set of indices inside comments or string/char literals (a match there is not code)."""
    inside, i = set(), 0
    while i < len(text):
        if text[i] in "\"'" or text.startswith("//", i) or text.startswith("/*", i):
            j = skip_literal(text, i)
            inside.update(range(i, j))
            i = j
        else:
            i += 1
    return inside


def convert_text(text, pkg, path, notes):
    """-> (new text, number of sites changed)."""
    compat = f"{pkg}.SavedDataCompat"
    n = 0
    # storage variables declared with the 1.21.1 type (before the type is renamed)
    storage_vars = set(re.findall(r"\b(?:" + re.escape(DDS_FQN) + r"|DimensionDataStorage)\s+(\w+)\s*[=;,)]", text))

    # 1. the SavedData subclasses
    text, k = re.subn(r"\bextends\s+(?:" + re.escape(SD_FQN) + r"|SavedData)\b(?![\w.])", f"extends {compat}.Base", text)
    n += k
    # 2. the Factory: nested import, then qualified uses
    text, k = re.subn(r"^import\s+" + re.escape(SD_FQN) + r"\.Factory\s*;", f"import {compat}.Factory;", text, flags=re.M)
    n += k
    text, k = re.subn(r"(?<![\w.])(?:" + re.escape(SD_FQN) + r"|SavedData)\.Factory\b", f"{compat}.Factory", text)
    n += k
    # 3. storage calls (factory, name) -> (type(factory, name))
    out, pos = [], 0
    masked = code_mask(text)
    for m in re.finditer(r"\.(computeIfAbsent|get|set)\s*\(", text):
        if m.start() in masked:
            continue
        before = text[:m.start()].rstrip()
        recv = re.search(r"(?:getDataStorage\(\)|\b(\w+))$", before)
        if not recv or (recv.group(1) and recv.group(1) not in storage_vars):
            continue
        open_i = m.end() - 1
        close_i = match_close(text, open_i)
        if close_i is None:
            continue
        args = split_args(text[open_i + 1:close_i])
        where = f"{path}:{line_of(text, m.start())}"
        if m.group(1) == "set":
            notes.append(f"REFUSED {where}: storage.set(name, data) -- 26.2's set takes the store's SavedDataType; "
                         f"build it with {compat}.type(factory, name)")
            continue
        if len(args) != 2:
            if not (len(args) == 1 and "SavedDataCompat.type(" in args[0]):
                notes.append(f"REFUSED {where}: storage.{m.group(1)}({len(args)} argument(s)) is not (factory, name)")
            continue
        out.append(text[pos:open_i + 1])
        out.append(f"{compat}.type({args[0].strip()}, {args[1].strip()})")
        pos = close_i
        n += 1
    out.append(text[pos:])
    text = "".join(out)
    # 4. the storage type itself
    text, k = re.subn(r"^import\s+" + re.escape(DDS_FQN) + r"\s*;", f"import {SDS_FQN};", text, flags=re.M)
    n += k
    text, k = re.subn(r"(?<![\w.])(?:" + re.escape(DDS_FQN) + r"|DimensionDataStorage)\b", "SavedDataStorage", text)
    if k and not re.search(r"^import\s+" + re.escape(SDS_FQN) + r"\s*;", text, re.M):
        text = re.sub(r"\bSavedDataStorage\b", SDS_FQN, text)   # no import to lean on: qualify it
    n += k
    # the SavedData import may now be unused: leave it (an unused import compiles; removing one is riskier)
    return text, n


def check_saves(text, path, notes):
    for m in re.finditer(r"class\s+(\w+)[^{]*\bextends\s+[\w.]*SavedDataCompat\.Base\b", text):
        if not re.search(r"\bCompoundTag\s+save\s*\(\s*(?:@\w+\s+)*(?:final\s+)?CompoundTag\s+\w+\s*,", text):
            notes.append(f"NOTE {path}:{line_of(text, m.start())}: {m.group(1)} has no save(CompoundTag, Provider); "
                         f"SavedDataCompat.Base requires one")


def convert(src, modid, pkg=None, dry=False):
    src = pathlib.Path(src)
    pkg = pkg or ((mod_package(src) or "") + ".compat").lstrip(".")
    if pkg == "compat":
        print("convert-saved-data: no @Mod class found; pass --package")
        return 1
    changed, notes, sites = [], [], 0
    for f in sorted(src.rglob("*.java")):
        t = f.read_text(encoding="utf-8", errors="replace")
        if GEN_TAG in t or not re.search(r"\bSavedData\b|DimensionDataStorage", t):
            continue
        rel = f.relative_to(src)
        new, k = convert_text(t, pkg, rel, notes)
        check_saves(new, rel, notes)
        if new != t:
            sites += k
            changed.append(f)
            if not dry:
                f.write_text(new, encoding="utf-8")
    if changed and not dry:
        out = src / pkg.replace(".", "/")
        out.mkdir(parents=True, exist_ok=True)
        (out / "SavedDataCompat.java").write_text(COMPAT.format(pkg=pkg, modid=modid, tag=GEN_TAG), encoding="utf-8")
    if not changed:
        print("convert-saved-data: nothing to do")
    else:
        print(f"convert-saved-data: {len(changed)} file(s) changed, {sites} site(s); {pkg}.SavedDataCompat")
    for line in notes:
        print(line)
    return 0


SAMPLE = {
    "a/Main.java": """package a;

@net.neoforged.fml.common.Mod("x")
public class Main {
}
""",
    "a/Bans.java": """package a;

import java.util.HashMap;
import java.util.Map;
import net.minecraft.core.HolderLookup;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.saveddata.SavedData;

public class Bans extends SavedData {
   private final Map<String, Integer> cache = new HashMap<>();

   public static Bans load(CompoundTag tag, HolderLookup.Provider provider) {
      return new Bans();
   }

   @Override
   public CompoundTag save(CompoundTag tag, HolderLookup.Provider provider) {
      return tag;
   }

   public static Bans get(ServerLevel level) {
      cache.computeIfAbsent("k", k -> 1);
      Integer x = cache.get("k");
      return (Bans)level.getDataStorage().computeIfAbsent(new SavedData.Factory<>(Bans::new, Bans::load), "x_bans");
   }

   // reached through level.getDataStorage().computeIfAbsent(...) at runtime
   public static Bans other(ServerLevel level) {
      return level.getDataStorage().computeIfAbsent(
         new SavedData.Factory<>(
            Bans::new,
            (tag, registries) -> load(tag, registries)
         ),
         "x_other"
      );
   }
}
""",
    "a/Sched.java": """package a;

import net.minecraft.core.HolderLookup.Provider;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.server.level.ServerLevel;
import net.minecraft.world.level.saveddata.SavedData;
import net.minecraft.world.level.saveddata.SavedData.Factory;
import net.minecraft.world.level.storage.DimensionDataStorage;

public class Sched extends SavedData {
   private static final Factory<Sched> FACTORY = new Factory<>(Sched::new, Sched::new);

   public Sched() {
   }

   public Sched(CompoundTag tag, Provider registries) {
   }

   public CompoundTag save(CompoundTag tag, Provider registries) {
      return tag;
   }

   static Sched get(ServerLevel level) {
      DimensionDataStorage storage = level.getDataStorage();
      Sched found = storage.get(FACTORY, "event_scheduler");
      storage.set("event_scheduler", found);
      return found != null ? found : storage.computeIfAbsent(
         FACTORY, "event_scheduler"
      );
   }
}
""",
    "a/Event.java": """package a;

import net.minecraft.core.HolderLookup;
import net.minecraft.nbt.CompoundTag;

public class Event {
   static Object get(net.minecraft.server.level.ServerLevel level) {
      return level.getDataStorage().computeIfAbsent(
         new net.minecraft.world.level.saveddata.SavedData.Factory<>(Event.Data::new, Event.Data::load), "dragon_challenges"
      );
   }

   public static class Data extends net.minecraft.world.level.saveddata.SavedData {
      static Data load(CompoundTag tag, HolderLookup.Provider p) {
         return new Data();
      }

      public CompoundTag save(CompoundTag tag, HolderLookup.Provider p) {
         return tag;
      }
   }
}
""",
}


def self_check():
    ok = True

    def expect(cond, label):
        nonlocal ok
        if not cond:
            print("FAIL:", label)
            ok = False

    with tempfile.TemporaryDirectory() as d:
        src = pathlib.Path(d)
        for rel, body in SAMPLE.items():
            (src / rel).parent.mkdir(parents=True, exist_ok=True)
            (src / rel).write_text(body, encoding="utf-8")
        convert(src, "x")
        bans = (src / "a/Bans.java").read_text(encoding="utf-8")
        expect("public class Bans extends a.compat.SavedDataCompat.Base {" in bans, "extends rewritten")
        expect("@Override\n   public CompoundTag save(CompoundTag tag, HolderLookup.Provider provider) {" in bans, "save kept")
        expect('computeIfAbsent(a.compat.SavedDataCompat.type(new a.compat.SavedDataCompat.Factory<>(Bans::new, Bans::load), "x_bans"))'
               in bans, "computeIfAbsent wrapped")
        expect("// reached through level.getDataStorage().computeIfAbsent(...) at runtime" in bans, "a comment is untouched")
        expect(re.search(r'computeIfAbsent\(a\.compat\.SavedDataCompat\.type\(new a\.compat\.SavedDataCompat\.Factory<>\('
                         r'\s*Bans::new,\s*\(tag, registries\) -> load\(tag, registries\)\s*\), "x_other"\)\)', bans), "lambda loader")
        expect('cache.computeIfAbsent("k", k -> 1);' in bans and 'cache.get("k");' in bans, "a Map is untouched")
        sched = (src / "a/Sched.java").read_text(encoding="utf-8")
        expect("import a.compat.SavedDataCompat.Factory;" in sched, "nested Factory import")
        expect("import net.minecraft.world.level.storage.SavedDataStorage;" in sched, "storage import")
        expect("SavedDataStorage storage = level.getDataStorage();" in sched, "storage type")
        expect('storage.get(a.compat.SavedDataCompat.type(FACTORY, "event_scheduler"))' in sched, "get on a variable")
        expect('storage.computeIfAbsent(a.compat.SavedDataCompat.type(FACTORY, "event_scheduler"))' in sched, "multi-line call")
        expect('storage.set("event_scheduler", found);' in sched, "set left alone")
        ev = (src / "a/Event.java").read_text(encoding="utf-8")
        expect("extends a.compat.SavedDataCompat.Base" in ev and "new a.compat.SavedDataCompat.Factory<>(Event.Data::new" in ev,
               "fully qualified forms")
        gen = (src / "a/compat/SavedDataCompat.java").read_text(encoding="utf-8")
        expect('NAMESPACE = "x"' in gen and "package a.compat;" in gen, "compat generated")
        expect(gen.count("{") == gen.count("}"), "compat braces balance")
        snap = {p: p.read_text(encoding="utf-8") for p in src.rglob("*.java")}
        convert(src, "x")
        expect(snap == {p: p.read_text(encoding="utf-8") for p in src.rglob("*.java")}, "idempotent")
    print("self-check:", "OK" if ok else "FAILED")
    return 0 if ok else 1


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--src")
    ap.add_argument("--modid")
    ap.add_argument("--package", help="where SavedDataCompat goes (default: <the @Mod class's package>.compat)")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--self-check", action="store_true")
    a = ap.parse_args()
    if a.self_check:
        return self_check()
    if not (a.src and a.modid):
        ap.error("--src and --modid are required")
    return convert(a.src, a.modid, a.package, a.dry_run)


if __name__ == "__main__":
    sys.exit(main())
