#!/usr/bin/env python3
"""MultiBufferSource, which 26.2 declares nowhere, as a generated synchronous-over-deferred seam (CATALOG §V54, §V66).

    python3 tools/convert-buffer-seam.py --src src/main/java --modid mymod [--package my.mod.compat] [--dry-run]
    python3 tools/convert-buffer-seam.py --self-check

26.2 records drawing: a renderer hands geometry to a SubmitNodeCollector, which replays it later.  There is no
"ask for a VertexConsumer and write into it now".  Four ports in this project wrote the same answer by hand -- a
`Buffers` class with MultiBufferSource's shape that records each batch and submits it through the collector the
renderer bound with Buffers.pushCollector / popCollector.  This generates that class (the most evolved copy: a real
collector STACK because renderers nest, a camera stack that accepts null, one LOUD log line when nothing is bound)
plus <package>.MultiBufferSource, vanilla's own shape (a functional interface with a nested BufferSource), which
Buffers implements.  So the mod's types, lambdas and casts stay exactly as written and only names move:

    import net.minecraft.client.renderer.MultiBufferSource;   ->  import <package>.MultiBufferSource;
    net.minecraft.client.renderer.MultiBufferSource (written out) -> <package>.MultiBufferSource
    <anything>.renderBuffers().bufferSource() / .crumblingBufferSource()  ->  Buffers.current()
    MultiBufferSource.immediate(builder) is a static on the generated interface and answers the same seam.

WHAT IT DOES NOT DO, and says so.  An OVERRIDE of a vanilla or library render hook that took a MultiBufferSource
(RenderLayer.render, EntityRenderer.render, BlockEntityRenderer.render, a GeckoLib preRender ...) overrides nothing on
26.2: those became submit(...) / extractRenderState(...) over a render STATE, not the entity, and porting them is
per-class work.  Each is NAMED (NEEDS SUBMIT), so a reader gets a list instead of a wall of "does not override".
The rule for that port: bracket the draw in the new submit(...) with Buffers.pushCollector(collector, camera) /
Buffers.popCollector() and the old body's getBuffer calls draw again.

Writes <package>.Buffers (default <the @Mod class's package>.compat) only when it rewrote something.  Idempotent.
Standard library only.
"""
import argparse, pathlib, re, sys, tempfile

GEN_TAG = "Generated by tools/convert-buffer-seam.py"
IMPORT = re.compile(r"^import\s+net\.minecraft\.client\.renderer\.MultiBufferSource\s*;\s*\n", re.M)
FQ = re.compile(r"\bnet\.minecraft\.client\.renderer\.MultiBufferSource\b")
SOURCE_CALL = re.compile(r"(?:\b[\w.]+(?:\(\))?\.)?renderBuffers\(\)\s*\.\s*(?:bufferSource|crumblingBufferSource)\(\)")
OVERRIDE = re.compile(r"@Override\s+(?:public|protected)\s+[\w.<>\[\], ?]+\s+(\w+)\s*\(([^)]*)\bMultiBufferSource\b", re.S)

SEAM = """package {pkg};

import com.mojang.blaze3d.vertex.PoseStack;
import com.mojang.blaze3d.vertex.VertexConsumer;
import it.unimi.dsi.fastutil.floats.FloatArrayList;
import it.unimi.dsi.fastutil.ints.IntArrayList;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import javax.annotation.Nullable;
import net.minecraft.client.renderer.SubmitNodeCollector;
import net.minecraft.client.renderer.state.level.CameraRenderState;
import net.minecraft.client.renderer.rendertype.RenderType;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

/** {tag}: 26.2 declares MultiBufferSource nowhere; this is its shape over SubmitNodeCollector (CATALOG §V54, §V66). */
public final class Buffers implements MultiBufferSource.BufferSource {{
   private static final Logger LOGGER = LogManager.getLogger("{modid}/Buffers");
   private static final Buffers INSTANCE = new Buffers();
   private static @Nullable SubmitNodeCollector collector;
   private static final java.util.ArrayDeque<SubmitNodeCollector> STACK = new java.util.ArrayDeque<>();
   private static @Nullable CameraRenderState camera;
   private static final java.util.List<CameraRenderState> CAMERAS = new java.util.ArrayList<>();
   private static boolean warned;

   private final Map<RenderType, Recorder> open = new LinkedHashMap<>();

   private Buffers() {{
   }}

   public static void pushCollector(SubmitNodeCollector collector) {{
      pushCollector(collector, null);
   }}

   public static void pushCollector(SubmitNodeCollector collector, CameraRenderState camera) {{
      STACK.addLast(collector);
      CAMERAS.addLast(camera);
      Buffers.collector = collector;
      Buffers.camera = camera;
   }}

   public static void popCollector() {{
      INSTANCE.flush();
      if (!STACK.isEmpty()) {{
         STACK.removeLast();
      }}

      if (!CAMERAS.isEmpty()) {{
         CAMERAS.remove(CAMERAS.size() - 1);
      }}

      SubmitNodeCollector outer = STACK.peekLast();
      Buffers.collector = outer;
      Buffers.camera = CAMERAS.isEmpty() ? null : CAMERAS.get(CAMERAS.size() - 1);
   }}

   @Nullable
   public static SubmitNodeCollector collector() {{
      return collector;
   }}

   @Nullable
   public static CameraRenderState camera() {{
      return camera;
   }}

   public static Buffers current() {{
      return INSTANCE;
   }}

   @Override
   public VertexConsumer getBuffer(RenderType type) {{
      return this.open.computeIfAbsent(type, t -> new Recorder());
   }}

   @Override
   public void endBatch() {{
      this.flush();
   }}

   @Override
   public void endBatch(RenderType type) {{
      Recorder recorder = this.open.remove(type);
      if (recorder != null) {{
         submit(type, recorder);
      }}
   }}

   private void flush() {{
      if (!this.open.isEmpty()) {{
         List<Map.Entry<RenderType, Recorder>> batches = new ArrayList<>(this.open.entrySet());
         this.open.clear();

         for (Map.Entry<RenderType, Recorder> batch : batches) {{
            submit(batch.getKey(), batch.getValue());
         }}
      }}
   }}

   private static void submit(RenderType type, Recorder recorder) {{
      if (!recorder.isEmpty()) {{
         SubmitNodeCollector collector = Buffers.collector;
         if (collector == null) {{
            if (!warned) {{
               warned = true;
               LOGGER.error(
                  "No SubmitNodeCollector is bound, so nothing was drawn for {{}}. A renderer must bracket its "
                     + "submit(...) with Buffers.pushCollector/popCollector on this Minecraft version.",
                  type
               );
            }}
         }} else {{
            collector.submitCustomGeometry(new PoseStack(), type, (pose, buffer) -> recorder.replayInto(buffer));
         }}
      }}
   }}

   private static final class Recorder implements VertexConsumer {{
      private static final int OP_VERTEX = 0;
      private static final int OP_COLOR4 = 1;
      private static final int OP_COLOR1 = 2;
      private static final int OP_UV = 3;
      private static final int OP_UV1 = 4;
      private static final int OP_UV2 = 5;
      private static final int OP_NORMAL = 6;
      private static final int OP_LINE_WIDTH = 7;
      private final IntArrayList ops = new IntArrayList();
      private final IntArrayList ints = new IntArrayList();
      private final FloatArrayList floats = new FloatArrayList();

      boolean isEmpty() {{
         return this.ops.isEmpty();
      }}

      void replayInto(VertexConsumer out) {{
         int intAt = 0;
         int floatAt = 0;

         for (int i = 0; i < this.ops.size(); i++) {{
            switch (this.ops.getInt(i)) {{
               case OP_VERTEX:
                  out.addVertex(this.floats.getFloat(floatAt++), this.floats.getFloat(floatAt++), this.floats.getFloat(floatAt++));
                  break;
               case OP_COLOR4:
                  out.setColor(this.ints.getInt(intAt++), this.ints.getInt(intAt++), this.ints.getInt(intAt++), this.ints.getInt(intAt++));
                  break;
               case OP_COLOR1:
                  out.setColor(this.ints.getInt(intAt++));
                  break;
               case OP_UV:
                  out.setUv(this.floats.getFloat(floatAt++), this.floats.getFloat(floatAt++));
                  break;
               case OP_UV1:
                  out.setUv1(this.ints.getInt(intAt++), this.ints.getInt(intAt++));
                  break;
               case OP_UV2:
                  out.setUv2(this.ints.getInt(intAt++), this.ints.getInt(intAt++));
                  break;
               case OP_NORMAL:
                  out.setNormal(this.floats.getFloat(floatAt++), this.floats.getFloat(floatAt++), this.floats.getFloat(floatAt++));
                  break;
               case OP_LINE_WIDTH:
                  out.setLineWidth(this.floats.getFloat(floatAt++));
                  break;
               default:
                  throw new IllegalStateException("Unknown recorded vertex op");
            }}
         }}
      }}

      @Override
      public VertexConsumer addVertex(float x, float y, float z) {{
         this.ops.add(OP_VERTEX);
         this.floats.add(x);
         this.floats.add(y);
         this.floats.add(z);
         return this;
      }}

      @Override
      public VertexConsumer setColor(int r, int g, int b, int a) {{
         this.ops.add(OP_COLOR4);
         this.ints.add(r);
         this.ints.add(g);
         this.ints.add(b);
         this.ints.add(a);
         return this;
      }}

      @Override
      public VertexConsumer setColor(int argb) {{
         this.ops.add(OP_COLOR1);
         this.ints.add(argb);
         return this;
      }}

      @Override
      public VertexConsumer setUv(float u, float v) {{
         this.ops.add(OP_UV);
         this.floats.add(u);
         this.floats.add(v);
         return this;
      }}

      @Override
      public VertexConsumer setUv1(int u, int v) {{
         this.ops.add(OP_UV1);
         this.ints.add(u);
         this.ints.add(v);
         return this;
      }}

      @Override
      public VertexConsumer setUv2(int u, int v) {{
         this.ops.add(OP_UV2);
         this.ints.add(u);
         this.ints.add(v);
         return this;
      }}

      @Override
      public VertexConsumer setNormal(float x, float y, float z) {{
         this.ops.add(OP_NORMAL);
         this.floats.add(x);
         this.floats.add(y);
         this.floats.add(z);
         return this;
      }}

      @Override
      public VertexConsumer setLineWidth(float width) {{
         this.ops.add(OP_LINE_WIDTH);
         this.floats.add(width);
         return this;
      }}
   }}
}}
"""

IFACE = """package {pkg};

import com.mojang.blaze3d.vertex.VertexConsumer;
import net.minecraft.client.renderer.rendertype.RenderType;

/**
 * {tag}: 26.2 declares net.minecraft.client.renderer.MultiBufferSource nowhere (CATALOG §V54).  This is its shape,
 * unchanged -- a functional interface with a nested BufferSource -- so every type, lambda and cast in the mod stays
 * as written and only the import moves.  What hands one out (Buffers.current(), immediate(...)) is the recording
 * seam in Buffers, which draws through the SubmitNodeCollector the renderer bound (§V66).
 */
@FunctionalInterface
public interface MultiBufferSource {{
    VertexConsumer getBuffer(RenderType type);

    /** 1.21.1 handed a fresh immediate source over the given builder; 26.2 records, so this is the shared seam. */
    static BufferSource immediate(Object ignoredBuilder) {{
        return Buffers.current();
    }}

    interface BufferSource extends MultiBufferSource {{
        void endBatch();

        void endBatch(RenderType type);
    }}
}}
"""


def mod_package(src):
    for f in sorted(src.rglob("*.java")):
        t = f.read_text(encoding="utf-8", errors="replace")
        if re.search(r"^\s*@Mod\s*\(", t, re.M):
            m = re.search(r"^package\s+([\w.]+)\s*;", t, re.M)
            if m:
                return m.group(1)
    return None


def code_spans(text):
    """-> the text with string/char literals and comments blanked, same length (so offsets line up)."""
    out, i = list(text), 0
    while i < len(text):
        c = text[i]
        if c in "\"'":
            j = i + 1
            while j < len(text) and text[j] != c and text[j] != "\n":
                j += 2 if text[j] == "\\" else 1
            for k in range(i + 1, min(j, len(text))):
                out[k] = " "
            i = j + 1
        elif text.startswith("//", i):
            j = text.find("\n", i)
            j = len(text) if j < 0 else j
            for k in range(i, j):
                out[k] = " "
            i = j
        elif text.startswith("/*", i):
            j = text.find("*/", i + 2)
            j = len(text) if j < 0 else j + 2
            for k in range(i, j):
                if out[k] != "\n":
                    out[k] = " "
            i = j
        else:
            i += 1
    return "".join(out)


def sub_code(pattern, repl, text):
    """re.sub that ignores matches inside literals and comments."""
    mask, out, last, n = code_spans(text), [], 0, 0
    for m in pattern.finditer(mask):
        out.append(text[last:m.start()])
        out.append(repl(m) if callable(repl) else repl)
        last, n = m.end(), n + 1
    out.append(text[last:])
    return "".join(out), n


def add_import(text, fq):
    if re.search(r"^import\s+" + re.escape(fq) + r"\s*;", text, re.M):
        return text
    m = list(re.finditer(r"^import\s[^\n]*;\s*$", text, re.M))
    at = m[-1].end() if m else (re.search(r"^package\s[^\n]*;\s*$", text, re.M) or re.match("", text)).end()
    return text[:at] + f"\nimport {fq};" + text[at:]


def convert(src, modid, pkg=None, dry=False):
    src = pathlib.Path(src)
    pkg = pkg or ((mod_package(src) or "") + ".compat").lstrip(".")
    changed, sites, needs = [], 0, []
    for f in sorted(src.rglob("*.java")):
        t0 = t = f.read_text(encoding="utf-8", errors="replace")
        if GEN_TAG in t:
            continue
        rel = f.relative_to(src)
        for m in OVERRIDE.finditer(code_spans(t0)):
            line = t0.count("\n", 0, m.start()) + 1
            needs.append(f"{rel}:{line}: {m.group(1)}(...) overrides a render hook that took a MultiBufferSource")
        same_pkg = re.search(r"^package\s+" + re.escape(pkg) + r"\s*;", t, re.M)
        had_import = bool(IMPORT.search(t))
        t = IMPORT.sub("" if same_pkg else f"import {pkg}.MultiBufferSource;\n", t)
        t, a = sub_code(FQ, f"{pkg}.MultiBufferSource", t)
        a += int(had_import)
        t, b = sub_code(SOURCE_CALL, "Buffers.current()", t)
        if b and not same_pkg:
            t = add_import(t, f"{pkg}.Buffers")
        sites += a + b
        if t != t0:
            changed.append(rel)
            if not dry:
                f.write_text(t, encoding="utf-8")
    if changed and pkg and not dry:
        out = src / pkg.replace(".", "/")
        out.mkdir(parents=True, exist_ok=True)
        (out / "Buffers.java").write_text(SEAM.format(pkg=pkg, modid=modid, tag=GEN_TAG), encoding="utf-8")
        (out / "MultiBufferSource.java").write_text(IFACE.format(pkg=pkg, tag=GEN_TAG), encoding="utf-8")
    print(f"convert-buffer-seam: {len(changed)} file(s) changed; {sites} site(s) repointed at {pkg}.MultiBufferSource; "
          f"{len(needs)} render-hook override(s) need a hand port to submit(...)")
    for x in needs:
        print(f"  NEEDS SUBMIT {x}")
    return changed


SAMPLE = {
    "a/Mod.java": "package a;\n@Mod(\"x\")\npublic class Mod {}\n",
    "a/Layer.java": """package a;
import net.minecraft.client.renderer.MultiBufferSource;
public class Layer extends RenderLayer {
    @Override
    public void render(PoseStack pose, MultiBufferSource buffer, int light, Object e, float a, float b, float c, float d, float f, float g) {
        draw(pose, buffer);
    }
    static void draw(PoseStack pose, MultiBufferSource buffer) {
        VertexConsumer vc = buffer.getBuffer(RT);
        String s = "MultiBufferSource stays in a string";
    }
    static void go() { draw(null, Minecraft.getInstance().renderBuffers().bufferSource()); }
    static void lam() {
        MultiBufferSource.BufferSource delegate = MultiBufferSource.immediate(new ByteBufferBuilder(4096));
        MultiBufferSource forced = ignored -> delegate.getBuffer(RT);
        delegate.endBatch();
    }
}
""",
}


def self_check():
    ok = True
    with tempfile.TemporaryDirectory() as d:
        src = pathlib.Path(d)
        for rel, body in SAMPLE.items():
            (src / rel).parent.mkdir(parents=True, exist_ok=True)
            (src / rel).write_text(body, encoding="utf-8")
        convert(src, "x")
        t = (src / "a/Layer.java").read_text()
        ok &= "import a.compat.MultiBufferSource;" in t and "import net.minecraft.client.renderer.MultiBufferSource;" not in t
        ok &= "static void draw(PoseStack pose, MultiBufferSource buffer)" in t      # the type keeps its name
        ok &= "draw(null, Buffers.current());" in t and "import a.compat.Buffers;" in t
        ok &= "MultiBufferSource.immediate(new ByteBufferBuilder(4096));" in t     # a static on the interface
        ok &= "MultiBufferSource forced = ignored -> delegate.getBuffer(RT);" in t  # still a functional interface
        ok &= '"MultiBufferSource stays in a string"' in t
        seam = (src / "a/compat/Buffers.java").read_text()
        ok &= "implements MultiBufferSource.BufferSource" in seam and "pushCollector" in seam
        ok &= seam.count("@Override") == 11 and 'getLogger("x/Buffers")' in seam
        iface = (src / "a/compat/MultiBufferSource.java").read_text()
        ok &= "@FunctionalInterface" in iface and "static BufferSource immediate(Object" in iface
        snap = {p: p.read_text() for p in src.rglob("*.java")}
        convert(src, "x")
        ok &= snap == {p: p.read_text() for p in src.rglob("*.java")}
    print("self-check:", "OK" if ok else "FAILED")
    return 0 if ok else 1


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--src")
    ap.add_argument("--modid")
    ap.add_argument("--package", help="where Buffers goes (default: <the @Mod class's package>.compat)")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--self-check", action="store_true")
    a = ap.parse_args()
    if a.self_check:
        return self_check()
    if not (a.src and a.modid):
        ap.error("--src and --modid are required")
    convert(a.src, a.modid, a.package, a.dry_run)
    return 0


if __name__ == "__main__":
    sys.exit(main())
