#!/usr/bin/env python3
"""Move 1.21.1 data-attachment serialization (CompoundTag + HolderLookup.Provider) to 26.2 (ValueInput/ValueOutput),
keeping every body that reads or writes the tag byte-identical.

    python3 tools/convert-attachment-io.py --src src/main/java [--package my.mod.compat] [--dry-run]
    python3 tools/convert-attachment-io.py --self-check

26.2 changed NeoForge's attachment serializer from
    IAttachmentSerializer<CompoundTag, T>:  T read(IAttachmentHolder, CompoundTag, HolderLookup.Provider)
                                            @Nullable CompoundTag write(T, HolderLookup.Provider)
to  IAttachmentSerializer<T>:               T read(IAttachmentHolder, ValueInput)
                                            boolean write(T, ValueOutput)          (false = nothing to save)
and removed INBTSerializable (CATALOG §V51; the successor ValueIOSerializable takes ValueInput/ValueOutput).

A 1.21.1 attachment body is written against a CompoundTag, and NeoForge 26.2 keeps a lossless bridge to one:
ValueOutput.store(CompoundTag) merges the tag's entries at the top level (so the saved layout is byte-identical to
what 1.21.1 wrote) and ValueInput.read(MapCodec.assumeMapUnsafe(CompoundTag.CODEC)) hands the same entries back.
So the bodies are left alone and only the method headers change:

  read(IAttachmentHolder h, CompoundTag t, HolderLookup.Provider p) {      ->  read(IAttachmentHolder h, ValueInput nbtBridgeIn) {
                                                                                CompoundTag t = NbtBridge.tag(nbtBridgeIn);
                                                                                HolderLookup.Provider p = nbtBridgeIn.lookup();
  CompoundTag write(T x, HolderLookup.Provider p) {                         ->  boolean write(T x, ValueOutput nbtBridgeOut) {
                                                                                return NbtBridge.write(nbtBridgeOut, this.nbtBridge$write(x, NbtBridge.provider()));
                                                                            }
                                                                            private CompoundTag nbtBridge$write(T x, HolderLookup.Provider p) {   <- the original body
  IAttachmentSerializer<CompoundTag, T>                                     ->  IAttachmentSerializer<T>
  net.neoforged.neoforge.common.util.INBTSerializable                       ->  <package>.INBTSerializable, the same two-method
                                                                                1.21.1 interface, generated (so `implements`,
                                                                                @Override and generic bounds all stay as written)

THE PROVIDER ON WRITE.  26.2's write() is handed no registry lookup.  NbtBridge.provider() is the running server's
registry access (null with no server), which is what an attachment is saved against.  A write body that USES its
provider is reported (NOTE), so the reader knows where the value now comes from.

REFUSED and named (left untouched): IAttachmentSerializer over anything but CompoundTag (Tag, IntTag, ...: a
different bridge), a header the patterns do not recognise in a file that names IAttachmentSerializer<CompoundTag,
and AttachmentType.serializable(...) on an INBTSerializable class (26.2's serializable() takes ValueIOSerializable).

Writes <package>.NbtBridge and <package>.INBTSerializable (default <the @Mod class's package>.compat) when anything changed.  Idempotent.
Standard library only.
"""
import argparse, pathlib, re, sys, tempfile

GEN_TAG = "Generated by tools/convert-attachment-io.py"
TYPE = r"[\w.]+(?:<[\w.<>,?\[\] ]*>)?(?:\[\])*"
SER = re.compile(r"\bIAttachmentSerializer<\s*CompoundTag\s*,\s*")
SER_OTHER = re.compile(r"\bIAttachmentSerializer<\s*(?!CompoundTag\b)(\w+)\s*,")
READ = re.compile(r"(?P<pub>public\s+)?(?P<ret>" + TYPE + r")\s+read\(\s*(?:final\s+)?IAttachmentHolder\s+(?P<h>\w+)\s*,"
                  r"\s*(?:final\s+)?CompoundTag\s+(?P<t>\w+)\s*,\s*(?:final\s+)?HolderLookup\.Provider\s+(?P<p>\w+)\s*\)\s*\{")
WRITE = re.compile(r"(?:public\s+)?(?:@Nullable\s+)?CompoundTag\s+write\(\s*(?:final\s+)?(?P<vt>" + TYPE + r")\s+(?P<v>\w+)\s*,"
                   r"\s*(?:final\s+)?HolderLookup\.Provider\s+(?P<p>\w+)\s*\)\s*\{")
IMPORTS = {"ValueInput": "net.minecraft.world.level.storage.ValueInput",
           "ValueOutput": "net.minecraft.world.level.storage.ValueOutput",
           "CompoundTag": "net.minecraft.nbt.CompoundTag", "HolderLookup": "net.minecraft.core.HolderLookup"}

NBT_IFACE = """package {pkg};

import net.minecraft.core.HolderLookup;
import net.minecraft.nbt.Tag;

/** {tag}: NeoForge 26.2 removed INBTSerializable (CATALOG §V51); this is its 1.21.1 contract, unchanged. */
public interface INBTSerializable<T extends Tag> {{
    T serializeNBT(HolderLookup.Provider provider);

    void deserializeNBT(HolderLookup.Provider provider, T nbt);
}}
"""

BRIDGE = """package {pkg};

import com.mojang.serialization.MapCodec;
import net.minecraft.core.HolderLookup;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.server.MinecraftServer;
import net.minecraft.world.level.storage.ValueInput;
import net.minecraft.world.level.storage.ValueOutput;
import net.neoforged.neoforge.server.ServerLifecycleHooks;

/**
 * {tag}: the 1.21.1 attachment bodies were written against a CompoundTag; 26.2 hands a ValueInput/ValueOutput.
 * NeoForge keeps a lossless bridge between the two, so the bodies need not change (CATALOG §V31/§V51).
 */
public final class NbtBridge {{
    private static final MapCodec<CompoundTag> WHOLE = MapCodec.assumeMapUnsafe(CompoundTag.CODEC);

    private NbtBridge() {{
    }}

    /** Every entry the ValueInput holds, as the CompoundTag 1.21.1 handed the body. */
    public static CompoundTag tag(ValueInput input) {{
        return input.read(WHOLE).orElseGet(CompoundTag::new);
    }}

    /** 1.21.1's "return null to save nothing" is 26.2's "return false". The entries merge at the top level. */
    public static boolean write(ValueOutput output, CompoundTag tag) {{
        if (tag == null) {{
            return false;
        }}
        output.store(tag);
        return true;
    }}

    /** 26.2's write() is handed no registry lookup: the running server's, which is what attachments save against. */
    public static HolderLookup.Provider provider() {{
        MinecraftServer server = ServerLifecycleHooks.getCurrentServer();
        return server == null ? null : server.registryAccess();
    }}
}}
"""


def mod_package(src):
    for f in sorted(src.rglob("*.java")):
        t = f.read_text(encoding="utf-8", errors="replace")
        if re.search(r"^\s*@Mod\s*\(", t, re.M):
            m = re.search(r"^package\s+([\w.]+)\s*;", t, re.M)
            if m:
                return m.group(1)
    return None


def body_end(text, open_brace):
    depth, i = 0, open_brace
    while i < len(text):
        c = text[i]
        if c == '"':
            i += 1
            while i < len(text) and text[i] != '"':
                i += 2 if text[i] == "\\" else 1
        elif c == "'":
            i += 1
            while i < len(text) and text[i] != "'":
                i += 2 if text[i] == "\\" else 1
        elif text.startswith("//", i):
            i = text.find("\n", i)
            if i < 0:
                return None
        elif text.startswith("/*", i):
            i = text.find("*/", i) + 1
        elif c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return i
        i += 1
    return None


def indent_after(text, pos):
    """The indentation of the first non-blank line after pos (the body's), and of the line holding pos."""
    line_start = text.rfind("\n", 0, pos) + 1
    head = re.match(r"[ \t]*", text[line_start:]).group(0)
    m = re.search(r"\n([ \t]*)\S", text[pos:])
    return (m.group(1) if m else head + "    "), head


def add_imports(text, names, pkg_import=None):
    want = [IMPORTS[n] for n in names] + ([pkg_import] if pkg_import else [])
    missing = [w for w in want if not re.search(r"^import\s+" + re.escape(w) + r"\s*;", text, re.M)
               and not re.search(r"^import\s+" + re.escape(w.rsplit(".", 1)[0]) + r"\.\*\s*;", text, re.M)]
    if not missing:
        return text
    m = re.search(r"^package\s+[\w.]+\s*;\s*\n", text, re.M)
    at = m.end() if m else 0
    return text[:at] + "".join(f"\nimport {w};" for w in missing) + text[at:]


def convert_file(text, pkg):
    """(new text, notes, refused)."""
    notes, refused = [], []
    for m in SER_OTHER.finditer(text):
        refused.append(f"IAttachmentSerializer<{m.group(1)}, ...>: only CompoundTag is bridged")
    has_ser = bool(SER.search(text))
    has_nbt = bool(re.search(r"\bnet\.neoforged\.neoforge\.common\.util\.INBTSerializable\b", text))
    if not (has_ser or has_nbt):
        return text, notes, refused
    new = text
    if has_ser:
        nread, nwrite = len(READ.findall(new)), len(WRITE.findall(new))
        nser = len(re.findall(r"(?:\bnew|\bimplements)\s+" + SER.pattern, new))
        if nread < nser or nwrite < nser:
            refused.append(f"{nser} IAttachmentSerializer<CompoundTag, ...> but {nread} read / {nwrite} write header(s) "
                           "recognised; left untouched")
            return text, notes, refused
        new = SER.sub("IAttachmentSerializer<", new)

        def do_read(m):
            body, outer = indent_after(new_read_src[0], m.end())
            return (f"{m.group('pub') or ''}{m.group('ret')} read(IAttachmentHolder "
                    f"{m.group('h')}, ValueInput nbtBridgeIn) {{\n{body}CompoundTag {m.group('t')} = NbtBridge.tag(nbtBridgeIn);"
                    f"\n{body}HolderLookup.Provider {m.group('p')} = nbtBridgeIn.lookup();")
        new_read_src = [new]
        new = READ.sub(do_read, new)
        # write: the original body becomes a private method that the 26.2 override calls
        out, pos = [], 0
        for m in WRITE.finditer(new):
            end = body_end(new, m.end() - 1)
            if end is None:
                refused.append("unbalanced write() body; left untouched")
                return text, notes, refused
            body_text = new[m.end():end]
            if re.search(r"\b" + re.escape(m.group("p")) + r"\b", body_text):
                line = new.count("\n", 0, m.start()) + 1
                notes.append((line, f"write() uses its provider `{m.group('p')}`: on 26.2 it is NbtBridge.provider(), "
                                    "the running server's registry access"))
            body, outer = indent_after(new, m.end())
            out.append(new[pos:m.start()])
            out.append(f"public boolean write({m.group('vt')} {m.group('v')}, ValueOutput nbtBridgeOut) {{\n{body}return "
                       f"NbtBridge.write(nbtBridgeOut, this.nbtBridge$write({m.group('v')}, NbtBridge.provider()));\n{outer}}}"
                       f"\n\n{outer}private CompoundTag nbtBridge$write({m.group('vt')} {m.group('v')}, "
                       f"HolderLookup.Provider {m.group('p')}) {{")
            pos = m.end()
        out.append(new[pos:])
        new = "".join(out)
        new = add_imports(new, ["ValueInput", "ValueOutput", "CompoundTag", "HolderLookup"], f"{pkg}.NbtBridge")
    if has_nbt:
        new = re.sub(r"\bnet\.neoforged\.neoforge\.common\.util\.INBTSerializable\b", f"{pkg}.INBTSerializable", new)
        if re.search(r"AttachmentType\.serializable\(", new):
            refused.append("AttachmentType.serializable(...): 26.2's takes a ValueIOSerializable (serialize(ValueOutput) / "
                           "deserialize(ValueInput)); the 1.21.1 INBTSerializable contract does not satisfy it")
    return new, notes, refused


def run(src, pkg=None, dry=False):
    src = pathlib.Path(src)
    if pkg is None:
        base = mod_package(src)
        if base is None:
            if not any(convert_file(f.read_text(encoding="utf-8"), "x.y")[0] != f.read_text(encoding="utf-8") for f in src.rglob("*.java")):
                print("convert-attachment-io: nothing to do")
                return 0
            print("convert-attachment-io: no @Mod class found; pass --package")
            return 2
        pkg = base + ".compat"
    changed, all_notes, all_refused = [], [], []
    for f in sorted(src.rglob("*.java")):
        t = f.read_text(encoding="utf-8")
        if GEN_TAG in t:
            continue
        new, notes, refused = convert_file(t, pkg)
        rel = f.relative_to(src)
        all_notes += [f"  NOTE {rel}:{ln}: {msg}" for ln, msg in notes]
        all_refused += [f"  REFUSED {rel}: {msg}" for msg in refused]
        if new != t:
            changed.append(rel)
            if not dry:
                f.write_text(new, encoding="utf-8")
    bridge = src / pkg.replace(".", "/") / "NbtBridge.java"
    if (changed or bridge.exists()) and not dry:
        bridge.parent.mkdir(parents=True, exist_ok=True)
        bridge.write_text(BRIDGE.format(pkg=pkg, tag=GEN_TAG), encoding="utf-8")
        (bridge.parent / "INBTSerializable.java").write_text(NBT_IFACE.format(pkg=pkg, tag=GEN_TAG), encoding="utf-8")
    print(f"convert-attachment-io: {len(changed)} file(s) changed" + (f"; {pkg}.NbtBridge" if changed else ""))
    for line in all_refused + all_notes:
        print(line)
    return 1 if all_refused else 0


FIXTURE = {
"com/example/att/AttMod.java": """package com.example.att;

@Mod("att")
public class AttMod {
}
""",
"com/example/att/Data.java": """package com.example.att;

import net.minecraft.core.HolderLookup;
import net.minecraft.nbt.CompoundTag;
import net.neoforged.neoforge.common.util.INBTSerializable;

public class Data implements INBTSerializable<CompoundTag> {
    int n;

    @Override
    public CompoundTag serializeNBT(HolderLookup.Provider provider) {
        CompoundTag t = new CompoundTag();
        t.putInt("n", n);
        return t;
    }

    @Override
    public void deserializeNBT(HolderLookup.Provider provider, CompoundTag tag) {
        n = tag.getIntOr("n", 0);
    }
}
""",
"com/example/att/Regs.java": """package com.example.att;

import net.minecraft.core.HolderLookup;
import net.minecraft.nbt.CompoundTag;
import net.neoforged.neoforge.attachment.IAttachmentHolder;
import net.neoforged.neoforge.attachment.IAttachmentSerializer;

public class Regs {
    static final Object X = AttachmentType.builder(Data::new)
            .serialize(new IAttachmentSerializer<CompoundTag, Data>() {
                @Override
                public Data read(IAttachmentHolder holder, CompoundTag tag, HolderLookup.Provider provider) {
                    Data d = new Data();
                    d.deserializeNBT(provider, tag);
                    return d;
                }

                @Override
                public CompoundTag write(Data data, HolderLookup.Provider provider) {
                    return data.serializeNBT(provider);
                }
            }).build();
}
""",
"com/example/att/Other.java": """package com.example.att;

public class Other implements IAttachmentSerializer<IntTag, Integer> {
}
""",
}


def self_check():
    ok = True

    def chk(label, cond):
        nonlocal ok
        if not cond:
            print("FAIL:", label)
            ok = False

    with tempfile.TemporaryDirectory() as t:
        src = pathlib.Path(t)
        for rel, body in FIXTURE.items():
            (src / rel).parent.mkdir(parents=True, exist_ok=True)
            (src / rel).write_text(body, encoding="utf-8")
        rc = run(src)
        regs = (src / "com/example/att/Regs.java").read_text(encoding="utf-8")
        data = (src / "com/example/att/Data.java").read_text(encoding="utf-8")
        chk("refused a non-CompoundTag serializer -> exit 1", rc == 1)
        chk("type argument dropped", "new IAttachmentSerializer<Data>()" in regs)
        chk("read header + bridge lines",
            "public Data read(IAttachmentHolder holder, ValueInput nbtBridgeIn) {\n                    CompoundTag tag = "
            "NbtBridge.tag(nbtBridgeIn);\n                    HolderLookup.Provider provider = nbtBridgeIn.lookup();" in regs)
        chk("read body untouched", "d.deserializeNBT(provider, tag);" in regs)
        chk("write override", "public boolean write(Data data, ValueOutput nbtBridgeOut) {\n                    return "
            "NbtBridge.write(nbtBridgeOut, this.nbtBridge$write(data, NbtBridge.provider()));\n                }" in regs)
        chk("original write body kept in the private method",
            "private CompoundTag nbtBridge$write(Data data, HolderLookup.Provider provider) {\n                    return "
            "data.serializeNBT(provider);" in regs)
        chk("imports", all(f"import {w};" in regs for w in ("net.minecraft.world.level.storage.ValueInput",
                                                             "net.minecraft.world.level.storage.ValueOutput",
                                                             "com.example.att.compat.NbtBridge")))
        chk("INBTSerializable retargeted, class otherwise untouched",
            data == FIXTURE["com/example/att/Data.java"].replace("net.neoforged.neoforge.common.util.", "com.example.att.compat."))
        chk("compat INBTSerializable generated", (src / "com/example/att/compat/INBTSerializable.java").is_file())
        chk("bridge generated", "assumeMapUnsafe" in (src / "com/example/att/compat/NbtBridge.java").read_text(encoding="utf-8"))
        chk("non-CompoundTag serializer untouched", (src / "com/example/att/Other.java").read_text(encoding="utf-8") == FIXTURE["com/example/att/Other.java"])
        snap = {p: p.read_bytes() for p in src.rglob("*") if p.is_file()}
        run(src)
        chk("idempotent", snap == {p: p.read_bytes() for p in src.rglob("*") if p.is_file()})
    print("self-check:", "OK" if ok else "FAIL")
    return 0 if ok else 1


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--src")
    ap.add_argument("--package", help="where NbtBridge goes (default: <the @Mod class's package>.compat)")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--self-check", action="store_true")
    a = ap.parse_args()
    if a.self_check:
        return self_check()
    if not a.src:
        ap.error("--src is required")
    return run(a.src, a.package, a.dry_run)


if __name__ == "__main__":
    sys.exit(main())
