#!/usr/bin/env python3
"""Three client hooks 26.2 removed, ported without editing a single method body (CATALOG §V51, §V52, §S4b).

    python3 tools/convert-client-hooks.py --src src/main/java --modid mymod [--package my.mod.compat] [--dry-run]
    python3 tools/convert-client-hooks.py --self-check

PARTICLES.  TextureSheetParticle folded into SingleQuadParticle, which wants its sprite in the constructor and
replaced getRenderType() with an abstract getLayer().  26.2 still has setSprite / setSpriteFromAge and the protected
`sprite` field, so <package>.TextureSheetParticle is generated: both 1.21.1 constructors (the sprite starts null and
is picked later, exactly as on 1.21.1, where a particle that never picked one also had none) plus pickSprite.  Then:
    public ParticleRenderType getRenderType() { return ParticleRenderType.PARTICLE_SHEET_OPAQUE; }
 -> protected SingleQuadParticle.Layer getLayer() { return SingleQuadParticle.Layer.OPAQUE; }
    (PARTICLE_SHEET_TRANSLUCENT -> TRANSLUCENT, TERRAIN_SHEET -> OPAQUE_TERRAIN, PARTICLE_SHEET_LIT -> OPAQUE, NOTED:
     brightness is getLightCoords' job now; any other body is REFUSED)
    getLightColor(float) -> getLightCoords(float)
    createParticle(T, ClientLevel, 6 doubles) gains the trailing RandomSource 26.2 passes (named portedRandom).

CLIENT EXTENSIONS.  Item.initializeClient / Block.initializeClient / MobEffect.initializeClient are declared nowhere
on 26.2, so an override overrides nothing and the item's renderer, armour model or overlay silently disappears
(§S4b).  RegisterClientExtensionsEvent exists on both versions.  The override keeps its body; the class gains
`implements <package>.ClientExtensionHooks.ForItem` (ForBlock, ForEffect), its @Override and a super call to the
removed vanilla method go; and <package>.ClientExtensionHooks registers every registered instance from the event.

ITEM PROPERTIES.  ItemProperties / ItemPropertyFunction have no Java successor: a property override is the client
item definition (assets/<ns>/items/<id>.json) now.  The imports are repointed to a generated <package>.ItemProperties
whose register() does nothing and LOGS ONCE PER ITEM what to write instead -- a loud no-op (§V52), never a silent one,
and never a compile error a dependant has to remove by hand.  Each site is NOTED here too.

Writes the compat classes only for what it converted.  Idempotent.  Standard library only.
"""
import argparse, pathlib, re, sys, tempfile

GEN_TAG = "Generated by tools/convert-client-hooks.py"
TSP_IMPORT = re.compile(r"^import\s+net\.minecraft\.client\.particle\.TextureSheetParticle\s*;", re.M)
TSP_USE = re.compile(r"\bextends\s+(?:net\.minecraft\.client\.particle\.)?TextureSheetParticle\b")
RENDER_TYPE = re.compile(r"(?:@Override\s+)?public\s+(?:net\.minecraft\.client\.particle\.)?ParticleRenderType\s+getRenderType\s*\(\s*\)\s*\{"
                         r"\s*return\s+(?:net\.minecraft\.client\.particle\.)?ParticleRenderType\.(\w+)\s*;\s*\}")
RENDER_TYPE_ANY = re.compile(r"\bParticleRenderType\s+getRenderType\s*\(\s*\)")
LAYERS = {"PARTICLE_SHEET_OPAQUE": "OPAQUE", "PARTICLE_SHEET_TRANSLUCENT": "TRANSLUCENT", "TERRAIN_SHEET": "OPAQUE_TERRAIN",
          "PARTICLE_SHEET_LIT": "OPAQUE"}
LIGHT = re.compile(r"\b(protected|public)\s+int\s+getLightColor\s*\(\s*float\b")
CREATE = re.compile(r"\bcreateParticle\s*\(\s*(?:final\s+)?[\w.<>?]+\s+\w+\s*,\s*(?:final\s+)?(?:[\w.]+\.)?ClientLevel\s+\w+"
                    r"(?:\s*,\s*(?:final\s+)?double\s+\w+){6}\s*\)")
HOOKS = {"Item": ("IClientItemExtensions", "ForItem"), "Block": ("IClientBlockExtensions", "ForBlock"),
         "MobEffect": ("IClientMobEffectExtensions", "ForEffect")}
INIT = re.compile(r"(?P<ann>@Override\s+)?public\s+void\s+initializeClient\s*\(\s*(?:final\s+)?(?:java\.util\.function\.)?"
                  r"Consumer\s*<\s*(?:[\w.]+\.)?(?P<ext>IClient(?:Item|Block|MobEffect)Extensions)\s*>\s+(?P<v>\w+)\s*\)\s*\{")
PROP_IMPORT = re.compile(r"^import\s+net\.minecraft\.client\.renderer\.item\.(ItemProperties|ItemPropertyFunction|"
                         r"ClampedItemPropertyFunction)\s*;", re.M)
PROP_CALL = re.compile(r"\bItemProperties\s*\.\s*(register\w*)\s*\(")

TSP = """package {pkg};

import net.minecraft.client.multiplayer.ClientLevel;
import net.minecraft.client.particle.SingleQuadParticle;
import net.minecraft.client.particle.SpriteSet;

/**
 * {tag}: 26.2 folded TextureSheetParticle into SingleQuadParticle (CATALOG §V51), which takes the sprite in its
 * constructor.  The 1.21.1 constructors are kept: the sprite starts null and is picked afterwards, exactly as on
 * 1.21.1 (where a particle that never picked one had none either).
 */
public abstract class TextureSheetParticle extends SingleQuadParticle {{
    protected TextureSheetParticle(ClientLevel level, double x, double y, double z) {{
        super(level, x, y, z, null);
    }}

    protected TextureSheetParticle(ClientLevel level, double x, double y, double z, double xd, double yd, double zd) {{
        super(level, x, y, z, xd, yd, zd, null);
    }}

    public void pickSprite(SpriteSet sprites) {{
        this.setSprite(sprites.get(this.random));
    }}
}}
"""

HOOK_FILE = """package {pkg};

import java.util.function.Consumer;
import net.minecraft.core.registries.BuiltInRegistries;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.client.extensions.common.IClientBlockExtensions;
import net.neoforged.neoforge.client.extensions.common.IClientItemExtensions;
import net.neoforged.neoforge.client.extensions.common.IClientMobEffectExtensions;
import net.neoforged.neoforge.client.extensions.common.RegisterClientExtensionsEvent;

/**
 * {tag}: Item/Block/MobEffect.initializeClient are declared nowhere on 26.2, so an override overrides nothing and the
 * client extension silently disappears (CATALOG §S4b).  Each such class implements one of these, keeping its body,
 * and RegisterClientExtensionsEvent (present on both versions) registers every registered instance.
 */
@EventBusSubscriber(modid = "{modid}", value = Dist.CLIENT)
public final class ClientExtensionHooks {{
    public interface ForItem {{
        void initializeClient(Consumer<IClientItemExtensions> consumer);
    }}

    public interface ForBlock {{
        void initializeClient(Consumer<IClientBlockExtensions> consumer);
    }}

    public interface ForEffect {{
        void initializeClient(Consumer<IClientMobEffectExtensions> consumer);
    }}

    private ClientExtensionHooks() {{
    }}

    @SubscribeEvent
    public static void register(RegisterClientExtensionsEvent event) {{
        BuiltInRegistries.ITEM.forEach(item -> {{
            if (item instanceof ForItem hook) {{
                hook.initializeClient(ext -> event.registerItem(ext, item));
            }}
        }});
        BuiltInRegistries.BLOCK.forEach(block -> {{
            if (block instanceof ForBlock hook) {{
                hook.initializeClient(ext -> event.registerBlock(ext, block));
            }}
        }});
        BuiltInRegistries.MOB_EFFECT.forEach(effect -> {{
            if (effect instanceof ForEffect hook) {{
                hook.initializeClient(ext -> event.registerMobEffect(ext, effect));
            }}
        }});
    }}
}}
"""

PROPS = """package {pkg};

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import javax.annotation.Nullable;
import net.minecraft.client.multiplayer.ClientLevel;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.Identifier;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * {tag}: 26.2 has no ItemProperties -- an item's property overrides (a bow's pull, a crossbow's charge) are its
 * client item definition, assets/<ns>/items/<id>.json, a "minecraft:range_dispatch" / "minecraft:condition" model.
 * This keeps the 1.21.1 calls compiling and does nothing, LOUDLY: each item is logged once with what to write
 * (CATALOG §V52).  PROPERTIES answers an empty map for every item, so code that copies vanilla's bow properties
 * reads nothing rather than crashing.
 */
public final class ItemProperties {{
    private static final Logger LOGGER = LoggerFactory.getLogger("{modid}/ItemProperties");
    private static final Set<Item> WARNED = new HashSet<>();
    public static final Map<Item, Map<Identifier, ItemPropertyFunction>> PROPERTIES = new HashMap<>() {{
        @Override
        public Map<Identifier, ItemPropertyFunction> get(Object key) {{
            return key instanceof Item item ? this.computeIfAbsent(item, k -> new HashMap<>()) : null;
        }}
    }};

    private ItemProperties() {{
    }}

    public static void register(Item item, Identifier name, ItemPropertyFunction function) {{
        if (WARNED.add(item)) {{
            Identifier id = BuiltInRegistries.ITEM.getKey(item);
            LOGGER.warn("item property {{}} on {{}} is not applied: Minecraft 26.2 reads it from assets/{{}}/items/{{}}.json "
                    + "(a range_dispatch or condition model), not from Java", name, id, id.getNamespace(), id.getPath());
        }}
    }}

    public static void registerGeneric(Identifier name, ItemPropertyFunction function) {{
        LOGGER.warn("generic item property {{}} is not applied on Minecraft 26.2 (item properties are data now)", name);
    }}

    @FunctionalInterface
    public interface ItemPropertyFunction {{
        float call(ItemStack stack, @Nullable ClientLevel level, @Nullable LivingEntity entity, int seed);
    }}

    @FunctionalInterface
    public interface ClampedItemPropertyFunction extends ItemPropertyFunction {{
        float unclampedCall(ItemStack stack, @Nullable ClientLevel level, @Nullable LivingEntity entity, int seed);

        @Override
        default float call(ItemStack stack, @Nullable ClientLevel level, @Nullable LivingEntity entity, int seed) {{
            return Math.max(0.0F, Math.min(1.0F, this.unclampedCall(stack, level, entity, seed)));
        }}
    }}
}}
"""


def mod_package(src):
    for f in sorted(src.rglob("*.java")):
        t = f.read_text(encoding="utf-8", errors="replace")
        if re.search(r"^\s*@Mod\s*\(", t, re.M):
            m = re.search(r"^package\s+([\w.]+)\s*;", t, re.M)
            if m:
                return m.group(1)
    return None


def add_import(text, fq):
    simple = fq.rsplit(".", 1)[1]
    if re.search(r"^import\s+" + re.escape(fq) + r"\s*;", text, re.M):
        return text
    if re.search(r"^import\s+[\w.]+\." + re.escape(simple) + r"\s*;", text, re.M):
        return text
    m = list(re.finditer(r"^import\s[^\n]*;\s*$", text, re.M))
    at = m[-1].end() if m else (re.search(r"^package\s[^\n]*;\s*$", text, re.M) or re.match("", text)).end()
    return text[:at] + f"\nimport {fq};" + text[at:]


def enclosing_class(text, pos):
    """-> (name, header match) of the innermost class declaration before pos (by brace depth)."""
    best = None
    for m in re.finditer(r"\b(?:class|enum)\s+(\w+)(?:\s*<[^{]*?>)?(?P<rest>[^{;]*)\{", text[:pos]):
        depth = text[m.end():pos].count("{") - text[m.end():pos].count("}")
        if depth >= 0:
            best = m
    return best


def superclass_declares_init(header_rest, declares):
    m = re.search(r"\bextends\s+([\w.]+)", header_rest)
    return bool(m and m.group(1).split(".")[-1] in declares)


def convert_particles(text, pkg, notes, refused):
    n = 0
    if TSP_USE.search(text) or TSP_IMPORT.search(text):
        text = TSP_IMPORT.sub(f"import {pkg}.TextureSheetParticle;", text)
        if not re.search(r"^import\s+" + re.escape(pkg) + r"\.TextureSheetParticle\s*;", text, re.M) \
                and not re.search(r"^package\s+" + re.escape(pkg) + r"\s*;", text, re.M):
            text = add_import(text, f"{pkg}.TextureSheetParticle")
        text = re.sub(r"\bextends\s+net\.minecraft\.client\.particle\.TextureSheetParticle\b", "extends TextureSheetParticle", text)
        n += 1

    def layer(m):
        nonlocal n
        name = m.group(1)
        if name not in LAYERS:
            refused.append(f"getRenderType() returns ParticleRenderType.{name}: no SingleQuadParticle.Layer for it")
            return m.group(0)
        if name == "PARTICLE_SHEET_LIT":
            notes.append("PARTICLE_SHEET_LIT -> Layer.OPAQUE: a lit particle's brightness is getLightCoords now")
        n += 1
        return f"@Override\n    protected SingleQuadParticle.Layer getLayer() {{\n        return SingleQuadParticle.Layer.{LAYERS[name]};\n    }}"
    text = RENDER_TYPE.sub(layer, text)
    if RENDER_TYPE_ANY.search(text):
        refused.append("getRenderType() with a body other than `return ParticleRenderType.X;`")
    if "SingleQuadParticle.Layer" in text:
        text = add_import(text, "net.minecraft.client.particle.SingleQuadParticle")
    text, k = LIGHT.subn(lambda m: f"{m.group(1)} int getLightCoords(float", text)
    n += k

    def create(m):
        nonlocal n
        n += 1
        return m.group(0)[:-1].rstrip() + ", net.minecraft.util.RandomSource portedRandom)"
    if "ParticleProvider" in text:
        text = CREATE.sub(create, text)
    return text, n


def convert_extensions(text, pkg, declares, notes):
    n, used = 0, set()
    for m in reversed(list(INIT.finditer(text))):
        kind = {"IClientItemExtensions": "Item", "IClientBlockExtensions": "Block", "IClientMobEffectExtensions": "MobEffect"}[m.group("ext")]
        cls = enclosing_class(text, m.start())
        if not cls:
            continue
        chain = superclass_declares_init(cls.group("rest"), declares)
        body_start = m.end()
        head = m.group(0)
        if not chain:
            head = head.replace(m.group("ann") or "", "", 1)
            sup = re.compile(r"\s*super\s*\.\s*initializeClient\s*\(\s*" + re.escape(m.group("v")) + r"\s*\)\s*;")
            rest = sup.sub("", text[body_start:], count=1)
            text = text[:m.start()] + head + rest
        used.add((cls.start(), cls.group(1), HOOKS[kind][1]))
        n += 1
    for start, name, iface in sorted(used, reverse=True):
        cls = re.compile(r"\b(?:class|enum)\s+" + re.escape(name) + r"\b").search(text, start)
        brace = text.index("{", cls.end())
        header = text[cls.start():brace]
        full = f"{pkg}.ClientExtensionHooks.{iface}"
        if full in header:
            continue
        if re.search(r"\bimplements\b", header):
            header = re.sub(r"\bimplements\b", f"implements {full},", header, count=1)
        else:
            header = header.rstrip() + f" implements {full} "
        text = text[:cls.start()] + header + text[brace:]
    return text, n


def convert_props(text, pkg, notes):
    n = 0
    imports = PROP_IMPORT.findall(text)
    if not imports and not PROP_CALL.search(text):
        return text, 0
    for simple in imports:
        target = f"{pkg}.ItemProperties" if simple == "ItemProperties" else f"{pkg}.ItemProperties.{simple}"
        text = re.sub(r"^import\s+net\.minecraft\.client\.renderer\.item\." + simple + r"\s*;", f"import {target};", text, flags=re.M)
        n += 1
    sites = len(PROP_CALL.findall(text))
    if sites:
        notes.append(f"{sites} ItemProperties call(s) are a logged no-op on 26.2: write the property as a client item "
                     "definition (assets/<ns>/items/<id>.json, a range_dispatch or condition model)")
    return text, n + sites


def convert(src, modid, pkg=None, dry=False):
    src = pathlib.Path(src)
    files = [f for f in sorted(src.rglob("*.java")) if GEN_TAG not in f.read_text(encoding="utf-8", errors="replace")]
    pkg = pkg or ((mod_package(src) or "") + ".compat").lstrip(".")
    declares = set()
    for f in files:
        t = f.read_text(encoding="utf-8", errors="replace")
        for m in INIT.finditer(t):
            cls = enclosing_class(t, m.start())
            if cls:
                declares.add(cls.group(1))
    changed, counts, notes, refused, need = [], {"particles": 0, "extensions": 0, "properties": 0}, [], [], set()
    for f in files:
        t0 = t = f.read_text(encoding="utf-8", errors="replace")
        rel = f.relative_to(src)
        fn, fr = [], []
        # each part counts only when it changed the text, so a re-run reports 0 (idempotent and honest)
        t1, a = convert_particles(t, pkg, fn, fr)
        t2, b = convert_extensions(t1, pkg, declares, fn)
        t3, c = convert_props(t2, pkg, fn)
        a, b, c = (a if t1 != t else 0), (b if t2 != t1 else 0), (c if t3 != t2 else 0)
        if t3 == t2:
            fn[:] = [x for x in fn if "ItemProperties call" not in x]
        t = t3
        if f"{pkg}.TextureSheetParticle" in t:
            need.add("TextureSheetParticle")
        if f"{pkg}.ClientExtensionHooks" in t:
            need.add("ClientExtensionHooks")
        if f"{pkg}.ItemProperties" in t:
            need.add("ItemProperties")
        counts["particles"] += a
        counts["extensions"] += b
        counts["properties"] += c
        notes += [f"{rel}: {x}" for x in fn]
        refused += [f"{rel}: {x}" for x in fr]
        if t != t0:
            changed.append(rel)
            if not dry:
                f.write_text(t, encoding="utf-8")
    if need and pkg and not dry:
        out = src / pkg.replace(".", "/")
        out.mkdir(parents=True, exist_ok=True)
        for name, tmpl in (("TextureSheetParticle", TSP), ("ClientExtensionHooks", HOOK_FILE), ("ItemProperties", PROPS)):
            if name in need:
                (out / f"{name}.java").write_text(tmpl.format(pkg=pkg, tag=GEN_TAG, modid=modid), encoding="utf-8")
    print(f"convert-client-hooks: {len(changed)} file(s) changed; {counts['particles']} particle site(s), "
          f"{counts['extensions']} client extension(s), {counts['properties']} item-property site(s)"
          + (f"; {pkg}." + "/".join(sorted(need)) if need else ""))
    for x in notes:
        print(f"  NOTE {x}")
    for x in refused:
        print(f"  REFUSED {x}")
    return changed


SAMPLE = {
    "a/Mod.java": "package a;\n@Mod(\"x\")\npublic class Mod {}\n",
    "a/Snow.java": """package a;
import net.minecraft.client.particle.ParticleRenderType;
import net.minecraft.client.particle.TextureSheetParticle;
public class Snow extends TextureSheetParticle {
    protected Snow(ClientLevel l, double x, double y, double z) { super(l, x, y, z); }
    @Override
    public ParticleRenderType getRenderType() {
        return ParticleRenderType.PARTICLE_SHEET_TRANSLUCENT;
    }
    @Override
    protected int getLightColor(float pt) { return 240; }
    public static class Factory implements ParticleProvider<SimpleParticleType> {
        public Particle createParticle(SimpleParticleType t, ClientLevel level, double x, double y, double z, double dx, double dy, double dz) {
            Snow s = new Snow(level, x, y, z); s.pickSprite(sprites); return s;
        }
    }
}
""",
    "a/Gear.java": """package a;
import java.util.function.Consumer;
public class Gear extends ArmorItem {
    @Override
    public void initializeClient(Consumer<IClientItemExtensions> consumer) {
        super.initializeClient(consumer);
        consumer.accept(new IClientItemExtensions() {});
    }
}
""",
    "a/Child.java": """package a;
import java.util.function.Consumer;
public class Child extends Gear implements Comparable<Child> {
    @Override
    public void initializeClient(Consumer<IClientItemExtensions> consumer) {
        super.initializeClient(consumer);
    }
}
""",
    "a/Props.java": """package a;
import net.minecraft.client.renderer.item.ItemProperties;
import net.minecraft.client.renderer.item.ItemPropertyFunction;
public class Props {
    static void go() { ItemProperties.register(BOW, PULL, (s, l, e, i) -> 0f); }
}
""",
}


def self_check():
    ok = True
    with tempfile.TemporaryDirectory() as d:
        src = pathlib.Path(d)
        for rel, body in SAMPLE.items():
            (src / rel).parent.mkdir(parents=True, exist_ok=True)
            (src / rel).write_text(body, encoding="utf-8")
        convert(src, "x")
        s = (src / "a/Snow.java").read_text()
        ok &= "import a.compat.TextureSheetParticle;" in s and "getRenderType" not in s
        ok &= "return SingleQuadParticle.Layer.TRANSLUCENT;" in s and "int getLightCoords(float pt)" in s
        ok &= "double dz, net.minecraft.util.RandomSource portedRandom)" in s
        g = (src / "a/Gear.java").read_text()
        ok &= "implements a.compat.ClientExtensionHooks.ForItem" in g and "super.initializeClient" not in g and "@Override" not in g
        ok &= "consumer.accept(new IClientItemExtensions() {});" in g
        c = (src / "a/Child.java").read_text()
        ok &= "super.initializeClient(consumer);" in c and "@Override" in c      # its superclass is the mod's own
        ok &= "implements a.compat.ClientExtensionHooks.ForItem, Comparable<Child>" in c
        p = (src / "a/Props.java").read_text()
        ok &= "import a.compat.ItemProperties;" in p and "import a.compat.ItemProperties.ItemPropertyFunction;" in p
        for n in ("TextureSheetParticle", "ClientExtensionHooks", "ItemProperties"):
            ok &= (src / f"a/compat/{n}.java").exists()
        snap = {p: p.read_text() for p in src.rglob("*.java")}
        convert(src, "x")
        ok &= snap == {p: p.read_text() for p in src.rglob("*.java")}
    print("self-check:", "OK" if ok else "FAILED")
    return 0 if ok else 1


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--src")
    ap.add_argument("--modid")
    ap.add_argument("--package", help="where the compat classes go (default: <the @Mod class's package>.compat)")
    ap.add_argument("--dry-run", action="store_true")
    ap.add_argument("--self-check", action="store_true")
    a = ap.parse_args()
    if a.self_check:
        return self_check()
    if not (a.src and a.modid):
        ap.error("--src and --modid are required")
    convert(a.src, a.modid, a.package, a.dry_run)
    return 0


if __name__ == "__main__":
    sys.exit(main())
