#!/usr/bin/env python3
"""The Port CI kit: exactly the files a fork's CI needs to run its gates -- nothing else from this repository.

    python3 tools/port-ci-kit.py trace --repo <a ported fork checkout> --modid <id> [--base <ref>]
    python3 tools/port-ci-kit.py build --version N [--out DIR]       # kit tarball + MANIFEST.txt + SHA256SUMS
    python3 tools/port-ci-kit.py verify <kit.tar.gz>                 # unpack into an empty dir, self-check each tool
    python3 tools/port-ci-kit.py sha --version N                     # the sha256 `build` would produce, nothing written

A fork's CI (templates/upstream-harness/port-ci.yml) runs tools/ci-gates.py. It used to check this whole
repository out at a commit; it now downloads one release asset, `port-ci-kit-vN.tar.gz`, pinned by tag AND by
sha256. The kit is NOT a release of the migrator: it is the gate runner, the harness templates it renders and
the Gradle init scripts it passes, and only those.

What goes in is MEASURED, not guessed: `trace` runs ci-gates for real on a ported fork under strace and lists
every file of this repository that was opened or passed on a command line (a Gradle init script is handed to a
daemon by path, so it shows up in an execve argument rather than an open). The result is committed as
tools/port-ci-kit.txt -- the reviewed manifest `build` packs. A file the gates need on a path the traced run
did not take (a red gate's branch) lives in a module the green run already imported, so a green run covers it.

The archive is deterministic (sorted members, fixed mtime/owner, gzip with no name or time), so `sha` on a
commit reproduces a published asset's checksum -- that is how a fork's workflow pins it without trusting the
download. Standard library only (plus strace for `trace`).
"""
import argparse, gzip, hashlib, importlib.util, io, os, pathlib, re, shutil, subprocess, sys, tarfile, tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
LIST = ROOT / "tools/port-ci-kit.txt"
ENTRY = "tools/ci-gates.py"
HEADER = """# Port CI kit manifest: the files a fork's CI needs (tools/port-ci-kit.py). One path per line, relative
# to the repository root. Generated by `port-ci-kit.py trace` from a real green ci-gates run, then reviewed.
# Not a release of the migrator -- only what tools/ci-gates.py opens or passes on a command line.
"""


def _targets():
    spec = importlib.util.spec_from_file_location("targets", ROOT / "tools/targets.py")
    m = importlib.util.module_from_spec(spec); sys.modules.setdefault("targets", m); spec.loader.exec_module(m)
    return m


def read_list():
    return [l.strip() for l in LIST.read_text(encoding="utf-8").splitlines() if l.strip() and not l.startswith("#")]


def trace(repo, modid, base, gatec):
    log = pathlib.Path(tempfile.mkdtemp(prefix="kit-trace-")) / "strace.log"
    cmd = ["strace", "-f", "-qq", "-s", "4096", "-e", "trace=openat,execve", "-o", str(log),
           sys.executable, str(ROOT / ENTRY), "--repo", str(repo), "--modid", modid, "--gatec", gatec,
           "--summary", str(log.parent / "summary.md"), "--work-dir", str(log.parent / "work")]
    if base:
        cmd += ["--base", base]
    # a Gradle daemon started before the trace would read init scripts outside it; the paths still appear on
    # the gradle command lines, which the execve lines carry
    r = subprocess.run(cmd, capture_output=True, text=True, encoding="utf-8", errors="replace")
    print(r.stdout[-1500:])
    if r.returncode:
        sys.exit("ci-gates was not green under trace -- a kit is measured on a green run only")
    # the other targets' harness paths (a 1.21.1 run never opens the 26.2 rename table, client patch or GameTest
    # adapter): generate the harness for each, under the same trace, against the same fork
    logs = [log]
    for mc in sorted(_targets().TARGETS):
        if mc == _targets().target_of_repo(repo).mc:
            continue
        tl = log.parent / f"strace-harness-{mc}.log"
        snippet = ("import importlib.util,sys,types,pathlib;"
                   f"s=importlib.util.spec_from_file_location('pg',{str(ROOT / 'tools/port_gates.py')!r});"
                   "pg=importlib.util.module_from_spec(s);s.loader.exec_module(pg);"
                   f"c={{'repo':pathlib.Path({str(repo)!r}),'dir':pathlib.Path({str(log.parent / ('h-' + mc))!r}),"
                   f"'args':types.SimpleNamespace(modid={modid!r},base={base!r}),'target':pg.targets.TARGETS[{mc!r}]}};"
                   "pg.harness(c);print('harness ok')")
        r = subprocess.run(["strace", "-f", "-qq", "-s", "4096", "-e", "trace=openat,execve", "-o", str(tl),
                            sys.executable, "-c", snippet], capture_output=True, text=True, encoding="utf-8",
                           errors="replace")
        if "harness ok" not in r.stdout:
            sys.exit(f"generating the {mc} harness failed under trace: {(r.stderr or r.stdout)[-600:]}")
        logs.append(tl)
    root = str(ROOT) + "/"
    used = set()
    for line in (l for lg in logs for l in lg.read_text(encoding="utf-8", errors="replace").splitlines()):
        for m in re.finditer(re.escape(root) + r'([^"\s,\]\\]+)', line):
            p = m.group(1)
            # Python reads a fresh module from its bytecode cache and never opens the .py: map it back
            pc = re.match(r"(.*?)__pycache__/([^/.]+)\.[^/]*\.pyc$", p)
            if pc:
                p = pc.group(1) + pc.group(2) + ".py"
            if "__pycache__" in p or p.endswith(".pyc") or not (ROOT / p).is_file():
                continue
            used.add(p)
    used.add(ENTRY)
    LIST.write_text(HEADER + "\n".join(sorted(used)) + "\n", encoding="utf-8")
    print(f"{len(used)} file(s) -> {LIST.relative_to(ROOT)}")
    return 0


def build_bytes(version):
    files = read_list()
    missing = [f for f in files if not (ROOT / f).is_file()]
    if missing:
        sys.exit(f"kit manifest names files that do not exist: {missing}")
    if ENTRY not in files:
        sys.exit(f"kit manifest lacks its entry point {ENTRY}")
    raw = io.BytesIO()
    with tarfile.open(fileobj=raw, mode="w", format=tarfile.PAX_FORMAT) as t:
        manifest = (f"Port CI kit v{version}: the runtime for a ported fork's CI gates (tools/ci-gates.py).\n"
                    "Not a release of the migrator. Built from the files listed in tools/port-ci-kit.txt.\n\n"
                    + "".join(f"{hashlib.sha256((ROOT / f).read_bytes()).hexdigest()}  {f}\n" for f in files))
        for name, data, mode in [("MANIFEST.txt", manifest.encode("utf-8"), 0o644)] + \
                [(f, (ROOT / f).read_bytes(), 0o755 if os.access(ROOT / f, os.X_OK) else 0o644) for f in files]:
            ti = tarfile.TarInfo(name)
            ti.size, ti.mode, ti.mtime, ti.uid, ti.gid, ti.uname, ti.gname = len(data), mode, 0, 0, 0, "", ""
            t.addfile(ti, io.BytesIO(data))
    out = io.BytesIO()
    with gzip.GzipFile(filename="", mode="wb", fileobj=out, mtime=0) as g:
        g.write(raw.getvalue())
    return out.getvalue(), manifest


def build(version, out):
    data, manifest = build_bytes(version)
    out = pathlib.Path(out); out.mkdir(parents=True, exist_ok=True)
    name = f"port-ci-kit-v{version}.tar.gz"
    (out / name).write_bytes(data)
    (out / "MANIFEST.txt").write_text(manifest, encoding="utf-8")
    sha = hashlib.sha256(data).hexdigest()
    (out / "SHA256SUMS").write_text(f"{sha}  {name}\n", encoding="utf-8")
    print(f"{name}: {len(read_list())} file(s), sha256 {sha}")
    return 0


def verify(kit):
    """Unpack into an EMPTY directory and run every kit tool's self-check from there: a file the kit forgot
    fails here, at release time, instead of in some fork's CI."""
    d = pathlib.Path(tempfile.mkdtemp(prefix="kit-verify-"))
    with tarfile.open(kit, "r:gz") as t:
        t.extractall(d, filter="data")
    bad = []
    for py in sorted(d.glob("tools/*.py")):
        if "--self-check" not in py.read_text(encoding="utf-8", errors="replace"):
            continue
        r = subprocess.run([sys.executable, str(py), "--self-check"], cwd=d, capture_output=True, text=True,
                           encoding="utf-8", errors="replace", timeout=600)
        ok = r.returncode == 0 and "self-check: OK" in r.stdout
        print(f"  {'ok ' if ok else 'BAD'} {py.relative_to(d)}")
        if not ok:
            bad.append(f"{py.name}: {(r.stdout + r.stderr)[-400:]}")
    shutil.rmtree(d, ignore_errors=True)
    if bad:
        print("\n".join(bad)); return 1
    print("verify: every kit tool self-checks from the unpacked kit alone")
    return 0


def self_check():
    ok = ENTRY in read_list()
    a, _ = build_bytes(0)
    b, _ = build_bytes(0)
    ok &= a == b                                         # deterministic: the published sha can be reproduced
    names = tarfile.open(fileobj=io.BytesIO(a), mode="r:gz").getnames()
    ok &= names[0] == "MANIFEST.txt" and set(names[1:]) == set(read_list())
    ok &= not any(n.startswith(("mods/", "docs/", "CATALOG")) for n in names)
    print("self-check:", "OK" if ok else "FAIL")
    return 0 if ok else 1


def main():
    if "--self-check" in sys.argv:
        return self_check()
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    sub = ap.add_subparsers(dest="cmd", required=True)
    t = sub.add_parser("trace"); t.add_argument("--repo", required=True); t.add_argument("--modid", required=True)
    t.add_argument("--base"); t.add_argument("--gatec", default="launch,spawn,battle,gauntlet")
    b = sub.add_parser("build"); b.add_argument("--version", required=True); b.add_argument("--out", default="dist")
    v = sub.add_parser("verify"); v.add_argument("kit")
    s = sub.add_parser("sha"); s.add_argument("--version", required=True)
    a = ap.parse_args()
    if a.cmd == "trace":
        return trace(pathlib.Path(a.repo).resolve(), a.modid, a.base, a.gatec)
    if a.cmd == "build":
        return build(a.version, a.out)
    if a.cmd == "verify":
        return verify(a.kit)
    print(hashlib.sha256(build_bytes(a.version)[0]).hexdigest())
    return 0


if __name__ == "__main__":
    sys.exit(main())
