#!/usr/bin/env python3
"""Derive a RELEASE-aligned port from an existing port that was cut from the author's development branch.

    python3 tools/port-derive.py --repo <fork clone> --branch neoforge-1.21.1 --base origin/master \\
        --release <commit> [--new-branch neoforge-1.21.1-release] [--dry-run]
    python3 tools/port-derive.py --self-check

WHY.  A port cut from the tip of the author's branch carries every commit the author has NOT released (measured:
52 on one fork, two months of work in progress). Players expect the released behaviour. Porting the release from
scratch repeats work the existing port already did, because almost every change a port makes (renames, data
layout, build files, API moves) is identical either side of those commits.

HOW.  The port commits are the commits on --branch after --base that touch anything outside .github/ (the CI
workflow and install manifest are regenerated by tools/port-ci.py / port-offer.py, never replayed). They are
cherry-picked, oldest first, onto --release as --new-branch. Conflicts are resolved by rule, and every rule is
reported:

  only in unreleased code   the file does not exist at the release (DU: the port edited it, the release never had
                            it) -> dropped. The release does not have the feature; the port of it goes too.
  both changed              per conflicting HUNK, the port's side (cherry-pick -X theirs); the release's text is kept
                            everywhere else in the file. A hunk can still drag in a line of unreleased code; the
                            compiler names it.
  port-added, unreleased    a file the port ADDED whose imports name a class of the mod that no longer exists on
                            the new branch (a handler written for an unreleased feature) -> dropped, repeated until
                            none is left.

What remains is reported, never guessed: compile the branch (tools/burndown-count.sh) and the errors name each
leftover reference to unreleased code, typically a registration line in a list the port rewrote. Those are the
only part that needs a person or a model, and their count is the derivative port's cost.

Nothing is pushed. Standard library only.
"""
import argparse, pathlib, re, subprocess, sys, tempfile

DROP, KEEP_PORT, DROP_ADDED = "only in unreleased code", "both changed: port's side", "port-added for unreleased code"


def git(repo, *args, check=True):
    r = subprocess.run(["git", "-C", str(repo), *args], capture_output=True, text=True, encoding="utf-8")
    if check and r.returncode:
        raise SystemExit(f"git {' '.join(args)}: {r.stderr.strip()[:400]}")
    return r.stdout


def port_commits(repo, base, branch):
    out = []
    for line in git(repo, "log", "--reverse", "--format=%H %s", f"{base}..{branch}").splitlines():
        h, subject = line.split(" ", 1)
        files = [f for f in git(repo, "show", "--name-only", "--format=", h).splitlines() if f]
        if files and any(not f.startswith(".github/") for f in files):
            out.append((h, subject))
    return out


def conflicted(repo):
    rows = {}
    for line in git(repo, "status", "--porcelain").splitlines():
        code, path = line[:2], line[3:]
        if code in ("DU", "UD", "UU", "AA", "AU", "UA", "DD"):
            rows[path] = code
    return rows


def resolve(repo, report):
    for path, code in conflicted(repo).items():
        if code in ("DU", "DD"):
            git(repo, "rm", "-q", "-f", "--", path)
            report.append((DROP, path))
        elif code == "UD":                      # the port deleted a file the release still has: follow the port
            git(repo, "rm", "-q", "-f", "--", path)
            report.append(("deleted by the port", path))
        else:
            git(repo, "checkout", "-q", "--theirs", "--", path)
            git(repo, "add", "--", path)
            report.append((KEEP_PORT, path))


def mod_classes(repo, pkg_root):
    """Fully-qualified names of every class under the mod's package root, on the working tree."""
    out = set()
    for f in pathlib.Path(repo, "src/main/java").rglob("*.java"):
        rel = f.relative_to(pathlib.Path(repo, "src/main/java")).with_suffix("")
        fq = ".".join(rel.parts)
        if fq.startswith(pkg_root):
            out.add(fq)
    return out


def drop_orphans(repo, added, pkg_root, report):
    """Port-added files importing a mod class that no longer exists: drop, until stable."""
    while True:
        have = mod_classes(repo, pkg_root)
        gone = []
        for path in sorted(added):
            f = pathlib.Path(repo, path)
            if not f.is_file() or not path.endswith(".java"):
                continue
            imports = re.findall(r"^import\s+(?:static\s+)?(" + re.escape(pkg_root) + r"[\w.]*?)(?:\.\*|\.[a-z_]\w*)?\s*;",
                                 f.read_text(encoding="utf-8", errors="replace"), re.M)
            missing = [i for i in imports if i not in have and not any(h.startswith(i + ".") for h in have)
                       and not any(i.startswith(h + ".") for h in have)]
            if missing:
                gone.append((path, missing[0]))
        if not gone:
            return
        for path, why in gone:
            git(repo, "rm", "-q", "-f", "--", path)
            report.append((DROP_ADDED, f"{path} (imports {why.rsplit('.', 1)[-1]})"))


def prune_dead_imports(repo, pkg_root, report):
    """Imports of a MOD class (or package) that no longer exists -- it was unreleased -- are deleted. Only the mod's
    own packages: an import of another mod's class is never touched. A USE of the class is left for the compiler."""
    have = mod_classes(repo, pkg_root)
    pkgs = {c.rsplit(".", 1)[0] for c in have}
    for f in pathlib.Path(repo, "src/main/java").rglob("*.java"):
        text = f.read_text(encoding="utf-8")
        def dead(m):
            target = m.group(2)
            if m.group(3):                          # import pkg.* / Outer.*: alive if that package or class exists
                return target not in pkgs and target not in have
            while True:                             # a class, a nested class or a static member: alive if it
                if target in have:                  # or an enclosing class exists
                    return False
                if "." not in target or not target.startswith(pkg_root + "."):
                    return True
                target = target.rsplit(".", 1)[0]
        lines, out, n = text.split("\n"), [], 0
        for line in lines:
            m = re.match(r"^import\s+(static\s+)?(" + re.escape(pkg_root) + r"[\w.]*?)(\.\*)?\s*;\s*$", line)
            if m and dead(m):
                n += 1
                continue
            out.append(line)
        if n:
            f.write_text("\n".join(out), encoding="utf-8")
            report.append(("imports of unreleased classes removed", f"{f.relative_to(repo)} ({n})"))


def prune_mixin_configs(repo, report):
    """Drop mixin-config entries whose class no longer exists (it was unreleased): a missing mixin class is a crash
    at game start, which javac cannot see."""
    import json
    for cfg in pathlib.Path(repo, "src/main/resources").glob("*.mixins.json"):
        raw = cfg.read_text(encoding="utf-8")
        data = json.loads(raw)
        pkg = data.get("package", "")
        dropped = []
        for key in ("mixins", "client", "server"):
            keep = []
            for name in data.get(key, []):
                if pathlib.Path(repo, "src/main/java", *(pkg + "." + name).split(".")).with_suffix(".java").is_file():
                    keep.append(name)
                else:
                    dropped.append(name)
            if key in data:
                data[key] = keep
        if dropped:
            for name in dropped:      # edit the text, not a re-serialisation, so the file keeps its own layout
                raw = re.sub(r'\n[ \t]*"' + re.escape(name) + r'",?', "", raw)
            raw = re.sub(r",(\s*\])", r"\1", raw)
            cfg.write_text(raw, encoding="utf-8")
            json.loads(raw)
            git(repo, "add", "--", str(cfg.relative_to(repo)))
            report.extend(("mixin config: unreleased mixin removed", f"{cfg.name}: {n}") for n in dropped)


def derive(repo, branch, base, release, new_branch, pkg_root=None, dry=False):
    commits = port_commits(repo, base, branch)
    if not commits:
        raise SystemExit(f"no port commits on {branch} after {base}")
    if pkg_root is None:
        mods = git(repo, "grep", "-l", "-E", r"^\s*@Mod\(", branch, "--", "src/main/java", check=False).splitlines()
        if not mods:
            raise SystemExit("no @Mod class found; pass --package")
        text = git(repo, "show", mods[0])
        pkg_root = re.search(r"^package\s+([\w.]+)\s*;", text, re.M).group(1)
    ahead = int(git(repo, "rev-list", "--count", f"{release}..{base}").strip())
    print(f"port-derive: {len(commits)} port commit(s) to replay; the release is {ahead} commit(s) behind {base}")
    for h, s in commits:
        print(f"   {h[:9]} {s[:90]}")
    if dry:
        return 0
    git(repo, "checkout", "-q", "-B", new_branch, release)
    report, added = [], set()
    for h, subject in commits:
        added |= {l.split("\t")[-1] for l in git(repo, "show", "--name-status", "--format=", h).splitlines()
                  if l.startswith("A")}
        # -X theirs: only the CONFLICTING hunks take the port's side; everything else keeps the release's text.
        r = subprocess.run(["git", "-C", str(repo), "cherry-pick", "-X", "theirs", h], capture_output=True, text=True)
        if r.returncode:
            if not conflicted(repo):
                raise SystemExit(f"cherry-pick {h[:9]} failed without a conflict: {r.stderr.strip()[:300]}")
            resolve(repo, report)
            drop_orphans(repo, added, pkg_root, report)
            c = subprocess.run(["git", "-C", str(repo), "-c", "core.editor=true", "cherry-pick", "--continue"],
                               capture_output=True, text=True)
            if c.returncode:
                if "now empty" not in c.stdout + c.stderr:
                    raise SystemExit(f"cherry-pick {h[:9]} --continue: {(c.stdout + c.stderr).strip()[:300]}")
                git(repo, "cherry-pick", "--skip")       # it only touched unreleased code: nothing left to apply
                report.append(("skipped (only touched unreleased code)", f"{h[:9]} {subject[:70]}"))
    before = len(report)
    drop_orphans(repo, added, pkg_root, report)
    prune_mixin_configs(repo, report)
    prune_dead_imports(repo, pkg_root, report)
    git(repo, "add", "-A", "src")
    if len(report) > before:
        git(repo, "commit", "-q", "-m", "Drop port files that serve only unreleased features\n\n"
            + "\n".join(f"- {p}" for _, p in report[before:]))
    counts = {}
    for rule, _ in report:
        counts[rule] = counts.get(rule, 0) + 1
    print(f"port-derive: {new_branch} at {release[:9]} + {len(commits)} replayed commit(s); "
          + ("; ".join(f"{v} {k}" for k, v in counts.items()) or "no conflicts"))
    for rule, path in report:
        print(f"   {rule}: {path}")
    print("next: compile (tools/burndown-count.sh). Each remaining error is a leftover reference to unreleased "
          "code -- the derivative port's only manual cost.")
    return 0


def self_check():
    ok = True

    def chk(label, cond):
        nonlocal ok
        if not cond:
            print("FAIL:", label)
            ok = False

    with tempfile.TemporaryDirectory() as t:
        r = pathlib.Path(t)
        def w(path, body):
            p = r / path
            p.parent.mkdir(parents=True, exist_ok=True)
            p.write_text(body, encoding="utf-8")
        def commit(msg):
            git(r, "add", "-A")
            git(r, "-c", "user.name=t", "-c", "user.email=t@t", "commit", "-q", "-m", msg)
            return git(r, "rev-parse", "HEAD").strip()
        git(r, "init", "-q", "-b", "master")
        w("src/main/java/m/Mod.java", "package m;\n@Mod(\"m\")\nclass Mod {\n  void a() {}\n}\n")
        w("src/main/java/m/Reg.java", "package m;\nclass Reg {\n  int a = 1;\n}\n")
        release = commit("release 1.0")
        w("src/main/java/m/Reg.java", "package m;\nclass Reg {\n  int a = 1;\n  int boss = 2;\n}\n")   # unreleased
        w("src/main/java/m/Boss.java", "package m;\nclass Boss {}\n")
        commit("WIP boss bars")
        git(r, "checkout", "-q", "-b", "port")
        w("src/main/java/m/Mod.java", "package m;\n@Mod(\"m\")\nclass Mod {\n  void a(int ported) {}\n}\n")
        w("src/main/java/m/Reg.java", "package m;\nclass Reg {\n  long a = 1;\n  long boss = 2;\n}\n")
        w("src/main/java/m/Boss.java", "package m;\nclass Boss { int ported; }\n")
        w("src/main/java/m/net/BossHandler.java", "package m.net;\nimport m.Boss;\nclass BossHandler {}\n")
        w("src/main/java/m/net/Ok.java", "package m.net;\nimport m.Reg;\nclass Ok {}\n")
        commit("Port to NeoForge")
        w(".github/workflows/ci.yml", "x\n")
        commit("CI")
        rc = derive(r, "port", "master", release, "port-release")
        tree = set(git(r, "ls-files").split())
        chk("ran", rc == 0)
        chk("replayed onto the release", git(r, "merge-base", "--is-ancestor", release, "HEAD", check=False) == "")
        chk("clean port change kept", "a(int ported)" in (r / "src/main/java/m/Mod.java").read_text(encoding="utf-8"))
        chk("unreleased file dropped", "src/main/java/m/Boss.java" not in tree)
        chk("port-added handler for it dropped", "src/main/java/m/net/BossHandler.java" not in tree)
        chk("port-added file for released code kept", "src/main/java/m/net/Ok.java" in tree)
        chk("CI commit not replayed", ".github/workflows/ci.yml" not in tree)
    print("self-check:", "OK" if ok else "FAIL")
    return 0 if ok else 1


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--repo"); ap.add_argument("--branch"); ap.add_argument("--base")
    ap.add_argument("--release", help="the commit the author released")
    ap.add_argument("--new-branch"); ap.add_argument("--package", help="the mod's root package (default: the @Mod class's)")
    ap.add_argument("--dry-run", action="store_true"); ap.add_argument("--self-check", action="store_true")
    a = ap.parse_args()
    if a.self_check:
        return self_check()
    if not (a.repo and a.branch and a.base and a.release):
        ap.error("--repo, --branch, --base and --release are required")
    return derive(pathlib.Path(a.repo), a.branch, a.base, a.release, a.new_branch or a.branch + "-release", a.package, a.dry_run)


if __name__ == "__main__":
    sys.exit(main())
