#!/usr/bin/env python3
"""The mechanical half of reviewing a contribution.  The judgement half is the review-contribution skill.

    python3 tools/review-pr.py --base origin/main --head HEAD            # a local branch
    python3 tools/review-pr.py --base origin/main --head pr-42 --json    # machine-readable

It checks out HEAD into a temporary worktree (your checkout is untouched), runs every gate there, and
reads the diff for what the gates cannot see.  Each finding is BLOCKING (the PR cannot merge as is)
or ATTENTION (a human or the skill must look and decide).  Exit 0 = no blocking finding, 1 = at least
one, 2 = could not run.

WHAT IT LOOKS FOR, beyond the gates
    identity     the contributor may not know the private name list; the gate uses it if configured
    binaries     any added file that is not text, and any new sha1 in an allowlist (widening a gate)
    security     added lines that fetch-and-run, eval, shell=True, disable TLS, touch credentials, or
                 give a workflow write permissions / pull_request_target
    gates        lines REMOVED from a gate or its self-test, fewer self-test cases, a check disabled
    catalogue    entries removed (the fidelity gate), new entries without Pattern / Fix / a symptom,
                 new entries with no number anywhere (a rule with no measurement behind it)
    scope        files outside the areas a contribution usually touches

Standard library only.
"""
import argparse, json, os, pathlib, re, shutil, subprocess, sys, tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent

GATES = [  # (name, argv relative to the worktree, needs names file?)
    ("ip", [sys.executable, "tools/check-no-ip.py", "--root", "."], True),
    ("fidelity", [sys.executable, "tools/check-catalog-fidelity.py", "--root", "."], False),
    ("vendored", [sys.executable, "tools/gen-vendored.py", "--check"], False),
]
# Every tools/test-*.sh in the PR's own tree is run too, DISCOVERED rather than listed: a hand-kept list
# silently stopped running two self-tests the day they were added. (test-review.sh calls this script with
# --skip-self-tests, so there is no recursion.)
GATE_FILES = re.compile(r"^(tools/check-[\w-]+\.py|tools/test-[\w-]+\.sh|tools/gen-vendored\.py|"
                        r"tools/install-hooks\.sh|tools/review-pr\.py|\.github/workflows/.+|CODEOWNERS|"
                        r"docs/catalog-external-paths\.tsv|VENDORED\.tsv)$")
# (the census is regenerated by every catalogue PR, so its churn is not a finding by itself; what
#  matters is checked below, by running the fidelity gate against the BASE branch's census)
USUAL_SCOPE = re.compile(r"^(CATALOG\.md|docs/|tools/|templates/|\.claude/skills/|README\.md|"
                         r"\.github/|CODEOWNERS|VENDORED\.tsv|setup$|\.gitignore$)")
SECURITY = [
    (r"(curl|wget)[^|\n]*\|\s*(ba|z)?sh\b", "pipes a download into a shell"),
    (r"\beval\s*[\(\"'$]", "eval"),
    (r"\bexec\s*\(", "exec()"),
    (r"shell\s*=\s*True", "subprocess with shell=True"),
    (r"verify\s*=\s*False|--insecure\b|-k\s+https?://|CURL_CA_BUNDLE=\s*$|GIT_SSL_NO_VERIFY", "disables TLS verification"),
    (r"\b(ssh-keygen|id_rsa|\.ssh/|\.aws/|\.netrc|ACTIONS_RUNTIME_TOKEN)", "touches credentials"),
    (r"\bsecrets\.|GITHUB_TOKEN|\bgh auth\b", "uses a repository secret or token (confirm it is needed and scoped)"),
    (r"\bchmod\s+(-R\s+)?[0-7]*7[0-7]{0,2}\s+/", "chmod on an absolute path"),
    (r"\brm\s+-rf?\s+(/|~|\$HOME)(\s|$)", "recursive delete of / or home"),
    (r"base64\s+(-d|--decode)|b64decode\(", "decodes an embedded blob"),
    (r"(urllib\.request|requests\.(get|post)|urlopen|curl |wget )", "network access (check it is pinned and verified)"),
    (r"pull_request_target", "pull_request_target workflow (runs with write access on untrusted code)"),
    (r"permissions:\s*write-all|contents:\s*write|pull-requests:\s*write", "workflow asks for write permissions"),
]
BLOCKING_SECURITY = {"pipes a download into a shell", "disables TLS verification", "touches credentials",
                     "recursive delete of / or home", "decodes an embedded blob",
                     "pull_request_target workflow (runs with write access on untrusted code)"}
ENTRY_START = re.compile(r"^(?:[A-Z]{1,2}\d+[a-z]?\.\s|\d{1,3}[a-z]?\.\s+\*\*|\*\*[A-Z]{1,2}\d+[a-z]?\.|- \*\*[A-Z]{1,2}\d+)")



def entry_labels(text):
    """Field labels an entry uses -- MUST match tools/propose-learnings.py's entry_labels, so a lesson the
    proposer accepts is never blocked here: **Pattern:**, **Pattern (1.21.2+):**, **Pattern → Error → Fix:**."""
    out = set()
    # a span must START with a label word: pairing every `**` breaks on a title that contains `*`
    for span in re.findall(r"\*\*(?=(?:Pattern|Error|Runtime|Symptom|Fix)\b)([^*\n]{1,120}?)\*\*", text):
        span = re.sub(r"\s*\([^)]*\)", "", span).strip().rstrip(":").strip()
        parts = [p.strip().rstrip(":").strip() for p in re.split(r"\s*(?:→|->)\s*", span)]
        if len(parts) > 1 or span != span.rstrip(":") or parts[0] in ("Pattern", "Fix", "Error", "Runtime", "Symptom"):
            out.update(parts)
    return out

def sh(*args, cwd=ROOT, check=True):
    return subprocess.run(list(args), cwd=cwd, capture_output=True, text=True, check=check, encoding="utf-8", errors="replace")


def read_env():
    env = {}
    p = ROOT / ".env.local"
    if p.is_file():
        for line in p.read_text(encoding="utf-8").splitlines():
            if "=" in line and not line.lstrip().startswith("#"):
                k, v = line.split("=", 1)
                env[k.strip()] = v.strip()
    return env


def added_lines(diff):
    """-> [(path, text)] for every added line, from a unified diff."""
    out, path = [], None
    for line in diff.splitlines():
        if line.startswith("+++ "):
            path = line[6:] if line.startswith("+++ b/") else None
        elif line.startswith("+") and not line.startswith("+++") and path:
            out.append((path, line[1:]))
    return out


def removed_lines(diff):
    out, path = [], None
    for line in diff.splitlines():
        if line.startswith("--- "):
            path = line[6:] if line.startswith("--- a/") else None
        elif line.startswith("-") and not line.startswith("---") and path:
            out.append((path, line[1:]))
    return out


def passed(out):
    m = re.search(r"(\d+) passed", out)
    return int(m.group(1)) if m else None


def find_bash():
    """Plain `bash` everywhere but Windows. There CreateProcess searches System32 BEFORE PATH, so
    "bash" is WSL's launcher, not Git Bash -- and every self-test 'ran' with no pass count. Git for
    Windows' own bash sits two levels above `git --exec-path` (<Git>/mingw64/libexec/git-core)."""
    if os.name == "nt":
        r = subprocess.run(["git", "--exec-path"], capture_output=True, text=True, encoding="utf-8", errors="replace")
        if r.returncode == 0 and r.stdout.strip():
            git_root = pathlib.Path(r.stdout.strip()).parents[2]
            for c in (git_root / "bin/bash.exe", git_root / "usr/bin/bash.exe"):
                if c.is_file():
                    return str(c)
    return "bash"


BASH = find_bash()


def run_self_test(tree, script):
    r = subprocess.run([BASH, script], cwd=tree, capture_output=True, text=True, encoding="utf-8", errors="replace")
    return passed(r.stdout + r.stderr)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--base", default="origin/main")
    ap.add_argument("--head", default="HEAD")
    ap.add_argument("--names", help="forbidden-name list (default: FORBIDDEN_NAMES_FILE from .env.local)")
    ap.add_argument("--skip-self-tests", action="store_true", help="run only the fast gates")
    ap.add_argument("--json", action="store_true")
    a = ap.parse_args()

    for ref in (a.base, a.head):
        if sh("git", "rev-parse", "--verify", "--quiet", ref, check=False).returncode:
            print(f"review-pr: unknown ref {ref}", file=sys.stderr)
            return 2
    merge_base = sh("git", "merge-base", a.base, a.head).stdout.strip()
    diff = sh("git", "diff", "--no-color", "--no-ext-diff", "-U0", merge_base, a.head).stdout
    changed = [l.split("\t") for l in sh("git", "diff", "--name-status", "--no-renames", merge_base, a.head)
               .stdout.splitlines() if l]
    numstat = {l.split("\t")[2]: l.split("\t")[:2] for l in sh("git", "diff", "--numstat", merge_base, a.head)
               .stdout.splitlines() if l}
    findings = []

    def f(level, area, msg, where=""):
        findings.append({"level": level, "area": area, "message": msg, "where": where})

    # --- scope, binaries -------------------------------------------------------------------------
    for status, path in changed:
        if status != "D" and numstat.get(path, ["", ""])[0] == "-":
            f("BLOCKING", "binaries", "adds or changes a binary file (only the allowlisted Gradle wrapper and "
              "the generated test structure are permitted, by sha1)", path)
        if not USUAL_SCOPE.match(path):
            f("ATTENTION", "scope", "outside the areas a contribution usually touches", path)
        if GATE_FILES.match(path):
            f("ATTENTION", "gates", f"{'deletes' if status == 'D' else 'changes'} a gate, its test, CI or the "
              "catalogue inventory: read this file's diff line by line", path)
    for path, text in added_lines(diff):
        if path == "tools/check-no-ip.py" and re.search(r"\b[0-9a-f]{40}\b", text):
            f("BLOCKING", "gates", "adds a sha1 to the IP gate's allowlist: widening what may be committed "
              "needs the owner's explicit approval", path)

    # --- security --------------------------------------------------------------------------------
    for path, text in added_lines(diff):
        if path.endswith((".md", ".tsv")) or path in ("tools/review-pr.py", "tools/test-review.sh"):
            continue  # prose may DESCRIBE these; the reviewer's own patterns and planted fixtures name them
        if text.strip().startswith(("#", "//")):
            continue  # a comment cannot execute; flagging prose that DESCRIBES a risk is noise
        for rx, what in SECURITY:
            if re.search(rx, text):
                f("BLOCKING" if what in BLOCKING_SECURITY else "ATTENTION", "security", what,
                  f"{path}: {text.strip()[:140]}")

    # --- gate weakening --------------------------------------------------------------------------
    removed_from_gates = [(p, t) for p, t in removed_lines(diff) if GATE_FILES.match(p) and t.strip()
                          and not t.strip().startswith("#")]
    if removed_from_gates:
        f("ATTENTION", "gates", f"{len(removed_from_gates)} non-comment line(s) removed from gate/test/CI files; "
          "confirm each is a refactor, not a weakened check",
          "; ".join(f"{p}: {t.strip()[:60]}" for p, t in removed_from_gates[:5]))
    for path, text in added_lines(diff):
        if path.startswith(".github/workflows/") and re.search(r"continue-on-error:\s*true|if:\s*false|\|\|\s*true", text):
            f("BLOCKING", "gates", "a CI step can no longer fail", f"{path}: {text.strip()}")

    # --- catalogue -------------------------------------------------------------------------------
    cat_added = [t for p, t in added_lines(diff) if p == "CATALOG.md"]
    for t in cat_added:
        if ENTRY_START.match(t):
            labels = entry_labels(t)
            has = lambda word: word in labels
            miss = [f"**{k}:**" for k in ("Pattern", "Fix") if not has(k)]
            if not any(has(k) for k in ("Error", "Runtime", "Symptom")):
                miss.append("a symptom (**Error:**/**Runtime:**/**Symptom:**)")
            if miss:
                f("BLOCKING", "catalogue", f"new entry lacks {', '.join(miss)}: it cannot be found from the symptom "
                  "a porter is looking at", t[:100])
            if not re.search(r"\d", re.sub(r"^\S+", "", t)):
                f("ATTENTION", "catalogue", "new entry carries no number at all (no measurement, count, version "
                  "or error code): is it evidenced?", t[:100])
    cat_removed = [t for p, t in removed_lines(diff) if p == "CATALOG.md" and ENTRY_START.match(t)]
    if cat_removed:
        f("ATTENTION", "catalogue", f"{len(cat_removed)} entry line(s) removed or rewritten; the fidelity gate "
          "says whether any entry vanished", "; ".join(t[:50] for t in cat_removed[:4]))

    # --- the gates themselves, run on the PR's own tree ------------------------------------------
    names = a.names or read_env().get("FORBIDDEN_NAMES_FILE", "")
    names = os.path.expanduser(names) if names else ""
    wt = pathlib.Path(tempfile.mkdtemp(prefix="review-pr-"))
    gate_results = {}
    name_note = None
    try:
        sh("git", "worktree", "add", "-q", "--detach", str(wt), a.head)
        # Judge the PR's catalogue against the census it started from, not the one it ships: a PR that
        # deletes an entry AND its census row would otherwise pass the fidelity gate it just edited.
        base_census = sh("git", "show", f"{merge_base}:docs/catalog-census.tsv", check=False)
        if base_census.returncode == 0:
            (wt / "docs/catalog-census.tsv").write_text(base_census.stdout, encoding="utf-8")
        gates = list(GATES) + [(p.stem.replace("test-", "") + "-self-test", [BASH, f"tools/{p.name}"], False)
                               for p in sorted((wt / "tools").glob("test-*.sh"))]
        for name, argv, wants_names in gates:
            if a.skip_self_tests and "self-test" in name:
                continue
            if not (wt / argv[1]).exists():
                gate_results[name] = "absent"
                continue
            cmd = list(argv)
            if wants_names:
                if names and pathlib.Path(names).is_file():
                    cmd += ["--names", names, "--strict"]
                elif names:                       # configured but missing: a misconfiguration, say so
                    f("ATTENTION", "identity", f"the forbidden-name list {names} does not exist: the IP gate ran "
                      "without it. Fix the path, or unset it.")
                else:                             # the list is OPTIONAL: identity is the judgement pass's job
                    name_note = "no private name list (optional); read added lines for mod names by hand"
            r = subprocess.run(cmd, cwd=wt, capture_output=True, text=True, encoding="utf-8", errors="replace")
            gate_results[name] = "PASS" if r.returncode == 0 else "FAIL"
            if "self-test" in name and r.returncode == 0:
                gate_results[name] += f" ({passed(r.stdout + r.stderr)})"
            if r.returncode:
                tail = (r.stdout + r.stderr).strip().splitlines()[-6:]
                f("BLOCKING", "gate:" + name, "gate failed on the PR's tree", " | ".join(tail))
        # a self-test that asserts LESS than it did is a weakened gate, even when it passes
        changed_tests = [p for st, p in changed if st != "D" and re.match(r"tools/test-[\w-]+\.sh$", p)]
        if changed_tests:
            bt = pathlib.Path(tempfile.mkdtemp(prefix="review-base-"))
            try:
                sh("git", "worktree", "add", "-q", "--detach", str(bt), merge_base)
                for p in changed_tests:
                    if not (bt / p).exists():
                        continue
                    before, after = run_self_test(bt, p), run_self_test(wt, p)
                    if before is not None and (after is None or after < before):
                        f("BLOCKING", "gates", f"self-test assertions fell {before} -> {after}", p)
            finally:
                sh("git", "worktree", "remove", "--force", str(bt), check=False)
                shutil.rmtree(bt, ignore_errors=True)
    finally:
        sh("git", "worktree", "remove", "--force", str(wt), check=False)
        shutil.rmtree(wt, ignore_errors=True)

    blocking = [x for x in findings if x["level"] == "BLOCKING"]
    report = {"base": a.base, "head": a.head, "files": len(changed), "gates": gate_results,
              "blocking": len(blocking), "attention": len(findings) - len(blocking), "findings": findings}
    if a.json:
        print(json.dumps(report, indent=2))
    else:
        print(f"review-pr: {len(changed)} file(s) changed, {a.base}...{a.head}")
        print("  gates: " + ", ".join(f"{k}={v}" for k, v in gate_results.items()))
        if name_note:
            print(f"  note: {name_note}")
        for x in findings:
            print(f"  [{x['level']}] {x['area']}: {x['message']}" + (f"\n      {x['where']}" if x["where"] else ""))
        print(f"review-pr: {len(blocking)} blocking, {len(findings) - len(blocking)} for attention")
    return 1 if blocking else 0


if __name__ == "__main__":
    sys.exit(main())
